// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfEDurvzrx76r2bKradXYZnn4zkQ0H0Y',
    appId: '1:715074221772:web:8cbf5702662b304ccfb469',
    messagingSenderId: '715074221772',
    projectId: 'kwasi-45e3f',
    authDomain: 'kwasi-45e3f.firebaseapp.com',
    storageBucket: 'kwasi-45e3f.appspot.com',
    measurementId: 'G-NDSD8S9HJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6woAtFamMmEjIwgDymtRsSX2ceBvoTI0',
    appId: '1:715074221772:android:1cabe81cda2adac9cfb469',
    messagingSenderId: '715074221772',
    projectId: 'kwasi-45e3f',
    storageBucket: 'kwasi-45e3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe2jwKXGQlzBCfhhkFXpbNpa7p3iC6MHY',
    appId: '1:715074221772:ios:ffca696ccdf8013bcfb469',
    messagingSenderId: '715074221772',
    projectId: 'kwasi-45e3f',
    storageBucket: 'kwasi-45e3f.appspot.com',
    iosBundleId: 'com.app.kwasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe2jwKXGQlzBCfhhkFXpbNpa7p3iC6MHY',
    appId: '1:715074221772:ios:57ac2c66dcd4905acfb469',
    messagingSenderId: '715074221772',
    projectId: 'kwasi-45e3f',
    storageBucket: 'kwasi-45e3f.appspot.com',
    iosBundleId: 'com.app.kwasi.RunnerTests',
  );
}
