final List<Map<String,dynamic>> learningWords = [
    {
        "english": "Good morning! Time to wake up and start the day.",
        "french": "Bonjour! Il est temps de se réveiller et de commencer la journée.",
        "duala": "idiɓa á ɓwǎm̀, póndá tɛ́mɛ na ɓotea búnyá e máɗoŋgamɛnə",
        "ghomla": "o tí lə́!cwə nə́ du sǐ to' tyɛ̌'dzʉ̀",
        "bulu": "mbamba tyé! awɔlɔ yā vələ a táte ámǒs",
        "basaa": "Mɛ̀ ǹyegà à! Ŋgèdà lìtòdɛ̀ ì ŋ̀kɔlà inyùu ì ɓòdòl kɛl",
    },
    {
        "english": "I'm so excited for school today!",
        "french": "J'ai tellement hâte d'aller à l'école aujourd'hui !",
        "duala": "na malumalumanɛ ónyolá esukúlu á wɛ́ŋgɛ̄",
        "ghomla": "gaə̌ bo səŋnyə́ nə́ səkù tʉɔ̂'",
        "bulu": "mə nə məvak ású sikólo də́n",
        "basaa": "Mɛ̀ gwèe nyàmndà inyùu sùgulù i lɛ̌n ìni!",
    },
    {
        "english": "What's for breakfast? I'm hungry!",
        "french": "Qu'est-ce qu'il y a pour le petit-déjeuner ? J'ai faim!",
        "duala": "njé  i é ónyóló á ɗá lá idiba njai ni alédi mbá",
        "ghomla": "kə́ nə bvə̀nyə́ shwə̀? Zhíkù' wə́ jɛ́ á",
        "bulu": "étyam akak é nə jé? ma wók zae",
        "basaa": "Kii i yê inyùu jɛ i kɛkɛ̀là? Njàl ì gwèe mɛ̀.",
    },
    {
        "english": "Mom, where are my socks?",
        "french": "Maman, où sont mes chaussettes ?",
        "duala": "yeyɛ nyɔ́pinya ám̀ i e ndé ó wɛ́nī?",
        "ghomla": "kʉá , mstok mə́ há?",
        "bulu": "məmá bə sitɔ̂ bâm bə́ nə vé?",
        "basaa": "À îni, hɛɛ nyɔ̀piyà yɛ̂m i yê?",
    },
    {
        "english": "Oops, I forgot to brush my teeth. Better do that now.",
        "french": "Oups, j'ai oublié de me brosser les dents. Mieux vaut le faire maintenant.",
        "duala": "okoo na dímbédí ó sísa masoŋgá mám̀, ɓwám̀ ná ná ɓole  níka tatân",
        "ghomla": "yé , gaə̌ tʉɔnyə́ nə́ cù' msùŋ. Dzə́ gaə̌ grə́ cwəlɔ̌.",
        "bulu": "oops, ma tə́ vúan sukuban məsoŋ mâm. anə mfí yā bɔ̌ jǎm tə̄ éyɔŋ dí",
        "basaa": "Ây! Mɛ̀ ǹhoya sogòp, ǹsɛŋg lɛ mɛ sogōp nânɔ.",
    },
    {
        "english": "Yay, the school bus is here!",
        "french": "Ouais, le bus scolaire est là !",
        "duala": "uɛi mutóa mwá esukúlu mwé óa",
        "ghomla": "ééy mətwǎ səkú yəŋ!",
        "bulu": "yâh, mətóa yǎ sikólo anə vá",
        "basaa": "Halà, bûs ì sùgulù ì yè hâ.",
    },
    {
        "english": "I hope we have art class today. I love drawing!",
        "french": "J'espère que nous avons un cours d'art aujourd'hui. J'aime dessiner!",
        "duala": "na moŋgɛ́lɛ ná di mɛndɛ́ bɛ́nɛ ɓeléédí ɓá ɓolúlí wɛ́ŋgɛ̄. na tóndi duta",
        "ghomla": "gaə̌ kwɛ́ gə́ pə̌ ghə́ və səkú tʉɔ̀.gaə̌ kùŋ",
        "bulu": "ma búni nâ bî bǐ áyə́ə́lə́ də́n. Ma nyee me kaŋe",
        "basaa": "Mɛ̀ ḿɓōdol lɛ sùgulù ì lìkɛŋgɛ ì yè lɛ̀n, mɛ̀ ŋ́gwēs ŋ́òdâ",
    },
    {
        "english": "Who's my lunch buddy today?",
        "french": "Qui est mon copain du déjeuner aujourd'hui ?",
        "duala": "njá nyé dikɔ́m lám̀ lá ɗá lá kɔsi  wɛ́ŋgɛ̄",
        "ghomla": "a yá sǒ yə pyé gɔ ghɔ̂ bvənyə́ shwə́ tyɔ̌' a?",
        "bulu": "bía mot m̀bé bíá dí dén?",
        "basaa": "Njɛɛ à gaɓā i jɛ i kɛkɛ̀là lɛ̀n?",
    },
    {
        "english": "Recess is the best part of the day!",
        "french": "La récréation est le meilleur moment de la journée !",
        "duala": "páósɛ ni e ndé póndá ɓwǎm̀ nyá búnyá",
        "ghomla": "hʉitə́ bə cwə́ yé gaə̌ kùŋ nə́ tyɛ̌'dzʉ̀ lə́!",
        "bulu": "awɔ̌n é nə mbamba jam yǎ amǒs ",
        "basaa": "Nɔ̀yɛ̀ i ńtùk yɔn i yê looha lɔŋgɛ̂ i jâm i bìnjǎŋwa",
    },
    {
        "english": "Can I borrow a pencil, please?",
        "french": "Puis-je emprunter un crayon, s'il vous plaît ?",
        "duala": "na ená ná ɓálánɛ diwíndí lá tila sôn",
        "ghomla": "gaə̌ fíŋ nə́ hwû kùŋbvə́ a, səsó?",
        "bulu": "yə mə nə yóe ńkos wê engóngɔ́l?",
        "basaa": "Sɔhɔ̄, ɓàa mɛ̀ ńlà poôs liwindi jɔŋ ɛ?",
    },
    {
        "english": "I aced the math quiz! High five!",
        "french": "J'ai réussi le quiz de mathématiques ! Tape m'en cinq!",
        "duala": "na tɛ́ŋgɛ́nɛ kekisɛ lá musɔŋgí. mbákɛ́ mbá mítánu",
        "ghomla": "gaə̌ ghə̀m nə́ sɛ̌ ywə́ tyɔ̌'! Cwɔ́ yu pǔ nə́ yə̂!",
        "bulu": "ma tə́ kabe meve'ele mə́táŋ! ",
        "basaa": "Mɛ̀ ǹnɛ̂t man kèksɛ̀ mìnsɔ̀ŋgi. Ɓep mɛ̀ bitân!",
    },
    {
        "english": "I can't wait for lunch. Pizza day!",
        "french": "J'ai hâte de déjeuner. Journée pizza !",
        "duala": "na e musuŋga ó ɗá.  búnyá bwá ekɔkí a mukálá",
        "ghomla": "gaə̌ fiŋ nə pyáp cə́ŋ.yəŋ bə tyɛ̌' pizza",
        "bulu": "Mǝ́ tɔ̂ ojejae yā dī.  Amosǝ́ bǝ̄lǝ́t",
        "basaa": "Mɛ̀ ńyāmda ni ŋgǒŋ jɛ. Kɛl Pìzzâ!",
    },
    {
        "english": "The bell rang. It's time for science class.",
        "french": "La cloche sonna. C'est l'heure du cours de sciences.",
        "duala": "ŋgɛ́ŋ e májumba í e ndé póndá béléédí ɓá mbíákó",
        "ghomla": "pú ko' ŋwɛ́ .yəŋ cwə̌ nə́ danyə siaŋsə",
        "bulu": "Abǝŋgǝ́ é kɔ́bô yǎ.  Awɔlɔ míńyǝ́'ǝ́lán é kuí yǎ",
        "basaa": "Ŋgɛŋ ì ŋ̀kôt, ŋgèdà yìgîl i yi (sìâŋs)ì ŋ̀kɔlà.",
    },
    {
        "english": "My backpack is so heavy!",
        "french": "Mon sac à dos est tellement lourd !",
        "duala": "mukuta mwám̀ mwá mɔŋgɔ  mwé ɓodiló",
        "ghomla": "pwə́ á wə dzə́ te'",
        "bulu": "m̀fǝ́k wɔ̂m ó nǝ́ mbǝ̂ adǐt",
        "basaa": "Ɓɔ̀t yɛ̂m i sugùlù i ŋ́èt lɛ.",
    },
    {
        "english": "Can we play tag during recess?",
        "french": "Pouvons-nous jouer à chat pendant la récréation ?",
        "duala": "di ena dí oká loko lá síŋgi póndá páósɛs ,",
        "ghomla": "be pə́ fyə́ fyə pusì nə cwə̀fyə́ à?",
        "bulu": "Yǝ bí nǝ bɔ̌ bivoé bí ésíŋgi áwɔlɔ áwɔ̌n? ",
        "basaa": "Ɓàa dì ńlà tûk chat i ŋgèdà nɔ̀yɛ̀ i ńtùk ɛ̀?",
    },
    {
        "english": "I left my water bottle in the classroom.",
        "french": "J'ai laissé ma bouteille d'eau dans la classe.",
        "duala": "na dî epósí ám̀ yá madíɓá ó klǎsi",
        "ghomla": "gaə̌ tʉɔnyə̀ tù'shyə à dyə̌ səkú",
        "bulu": "Ma tǝ́ līk ńyɔmbe mǝ̄ndím wɔ̂m ábā sikólo",
        "basaa": "Mɛ̀ ǹyek pos yɛ̂m i malep i ndāp sùgulù.",
    },
    {
        "english": "The library is my favorite place. Let's read!",
        "french": "La bibliothèque est mon endroit préféré. Lisons!",
        "duala": "ɓolóŋgi ɓwá kálati  ndé ɓwé mbá epólo ná tɔ́dinɔ́ dí ɓɛ́ mbálɛ",
        "ghomla": "dyə̌ ŋwànyə̀ bə́ tsʉ' yé gaə̌ ŋkùŋ lə́. pə ké ywə́!",
        "bulu": "Ndâ bǝ kálatǝ e nǝ vóm mā nyǝǝ mǝtɔ̌. ńláŋe",
        "basaa": "Ndap bìkààt ì yè hɔ̀ma mɛ̀ ńlòha gwês. Di sɔŋglaga!",
    },
    {
        "english": "Time to line up for the assembly.",
        "french": "Il est temps de faire la queue pour l’assemblée.",
        "duala": "póndá tɛ́mɛ ó mulɔ́ŋ ónyóló á ɗoŋgámɛ́n e máɓotea ",
        "ghomla": "tàm nə ntɛ̌ ŋkɛ́ nə cu'tə̀ kù'",
        "bulu": "Awɔlɔ̌ yā tǝ́bǝ ńsāmbá é kuí yǎ",
        "basaa": "Ŋgèdà ì ŋ̀kɔla lɛ mɛ̀ tɛlɛp i ńlòŋ inyùu ǹtoŋ.",
    },
    {
        "english": "Who wants to be my partner for the project?",
        "french": "Qui veut être mon partenaire pour le projet ?",
        "duala": "njá nú māpúlɛ́ latɛ̌ ŋgoto na mbá ónyólo á mwano",
        "ghomla": "pyə́ wə̌ gɔ pə́mtə́ fà' yeŋ fà'?",
        "bulu": "Zá á yi nâ á bɔ mot wɔm ású ésae dí?",
        "basaa": "Njɛ à ńsombol ɓa liwanda jɛ̂m inyùu ɓòlo ?",
    },
    {
        "english": "I love when the teacher reads us a story.",
        "french": "J'aime quand le professeur nous lit une histoire.",
        "duala": "na tɔ́ndi kɛ́ muléedi a maláŋgéa bisɔ́ miaŋgós ó klǎsi",
        "ghomla": "Gaə̂ ŋkùŋ gaə̌ gɛ̌la'tə̀ tǎtə̀ potsə́.",
        "bulu": "Ma nyəə éyɔŋ ǹyə́lə a lân bía ǹláŋ",
        "basaa": "Mɛ̀ ŋ́gwēs i ŋgɛ̄ŋ màlêt à ńsɔ̄ŋglɛ ɓes ŋ̀ŋaŋ.",
    },
    {
        "english": "Gym class is so much fun!",
        "french": "Les cours de gym sont tellement amusants !",
        "duala": " loko lá kɔ́kɔ lá misisá lá e minysanɛ malɔ́di",
        "ghomla": "səkú bwənyə́ mà' mtiŋ té'",
        "bulu": "Ayə́'ə́lə́ Gym é nə m̀bə̂ fianga",
        "basaa": "Yìgîl i makwasi i ńnōhla ŋgandàk.",
    },
    {
        "english": "I got a gold star on my drawing. Proud moment!",
        "french": "J'ai une étoile dorée sur mon dessin. Moment de fierté !",
        "duala": " na ɓɛ́ǹ ŋgéŋgéti á gol ó mɔ́ny á duta póndá nyá kéndaki",
        "ghomla": "gaə̌ ghə́ sɛ̌ kyɛ'kyɛ cʉm tsə́ və́ mə.tàm nə́ ŋwɛ́nyə",
        "bulu": "Mə bilí ótétê ó fae ńkaŋán wɔ̂m. Ma wók məvak",
        "basaa": "Mɛ̀ ŋ̀kôs hyodok hi gôl inyùu ŋòdâ. Ŋgèdà ì lìhàn.",
    },
    {
        "english": "I hope we have a fun homework assignment today.",
        "french": "J'espère que nous aurons un devoir amusant aujourd'hui.",
        "duala": "na pitɛ̌ na di mɛndɛ́ ɓɛ́nɛ ɓeléédí  ɓá kuma wɛ́ŋgɛ̄",
        "ghomla": "gaə̌ kwɛ́ gə pə̀ gɔ́ piŋ ghə̌ mu' fà' ya gɔ mà'mtǐŋ a tʉɔ̀'",
        "bulu": "Mə tɔɔ́ aa ndi nâ bî bi bisae bíá wɔ́le",
        "basaa": "Mɛ̀ ḿɓōdol lɛ dì gaɓana lɔŋgɛ̂ i nôhlà i ńsɔ̄n lɛ̀n.",
    },
    {
        "english": "It's raining. I need my umbrella.",
        "french": "Il pleut. J'ai besoin de mon parapluie.",
        "duala": "mbúa nye ó wɔ́lɛ  na ɓɛ́ǹ nyɔ́ŋgí á mbulédi ám̀",
        "ghomla": "bəŋ wə dú. Gaə̂ bo cəŋ wɔ̌ktə̀",
        "bulu": "Mvəŋ ya nɔ́ŋ. Ma yi ngəŋga wɔm",
        "basaa": "Nɔ̌p à yè i nɔ. Mɛ̀ gwèe ŋgǒŋ nì ŋgàŋgò yɛ̀m.",
    },
    {
        "english": "I'm excited for show and tell!",
        "french": "J'ai hâte de montrer et de raconter !",
        "duala": "na e lumalumanɛ ónyólo á nyumanyuma na láŋgwa mɔ́",
        "ghomla": "gaə̌ bo səŋnyə́ nə́ yɔ́ biŋ gɔ̀m",
        "bulu": "Mə nə ojəjaé yā líti aa lân",
        "basaa": "Mɛ̀ ńnyāmda ni ŋgòŋ i ebâ nì i aŋlɛ̀.",
    },
    {
        "english": "The school day is almost over. Yay!",
        "french": "La journée d'école est presque terminée. Yay!",
        "duala": "búnyá ɓwá esukúlu ɓó ɓɔ́i.....uɛɛɛ",
        "ghomla": "yəŋ tyɛ̌' səkú bo cʉ' a muwə́ a mí.hmmm",
        "bulu": "Amosə́ sikólo ó mbə́mə man.Yay!",
        "basaa": "Kɛl ì sùgulù ì mâl yàa. Halà!",
    },
    {
        "english": "Can I have a snack when I get home?",
        "french": "Puis-je prendre une collation en rentrant à la maison ?",
        "duala": "na e ná ná seŋgá manyɛ́ŋgúnyɛŋgú  ó timba lá mbóa",
        "ghomla": "pə́ mo nə́ phənyə́ lá' jɔ́ tsʉ́' nə́ nwə́ wə à?",
        "bulu": "Yə mə nə nyɔŋ évaa sɔ́m éyɔŋ ma búlan ndá?",
        "basaa": "Ɓàa mɛ̀ ńlà kôs yɔm i jɛ i ŋgɛ̄ŋ mɛ̀ ńlɔ̀ hanânɔ i ndap ɛ?",
    },
    {
        "english": "I have soccer practice after       w  .   w   wschool today.",
        "french": "J'ai un entraînement de football après w. w wschool aujourd'hui.",
        "duala": "na ɓɛ́ǹ maŋgiŋgo má bɔ́l ó mbúsá ɓeléédí ɓá esukúlu ",
        "ghomla": "gaə̌ gɔ ghə tàm bâlɔŋ bwâdzʉ̌ ɔ",
        "bulu": "mə bilí mimbâlan də́n ḿvúsə sikólo",
        "basaa": "Mɛ̀ gwèe ǹtùk i bɔ̂l i mbūs sùgulù lɛ̀n.",
    },
    {
        "english": "Mom, can you help me with my homework?",
        "french": "Maman, peux-tu m'aider avec mes devoirs ?",
        "duala": "yeyɛ o ená óŋgwáné mbá ónyóló a eɓoló ám̀s ",
        "ghomla": "kʉa bə o hwitə̌ a nə́ mfà' səkú á mə á?",
        "bulu": "Məmá, yə o nə ma vɔ́lô aa bisaé bíam?",
        "basaa": "Îni, ù ńlà hola mɛ̂ i ɓɔ̀ŋ ǹsɔn wɛ̂m i sugulù ?",
    },
    {
        "english": "I finished my book report. Phew!",
        "french": "J'ai terminé mon rapport de lecture. Phew!",
        "duala": "na máɓɔ́lɛ ɓoláŋgí ɓwá kálati ám̀ áiii",
        "ghomla": "gaə̌ myəŋ nə́ ŋké ywə̌. Hm!",
        "bulu": "mə́ manəyǎ tili fɔ́é ǹláŋán jam. Títyɔ́é",
        "basaa": "Mɛ̀ m̀mâl mbogi ì lìsɔŋgɔ̂l jɛ̂m. Hâ!",
    },
    {
        "english": "I want to play video games for a bit.",
        "french": "J'ai envie de jouer un peu aux jeux vidéo.",
        "duala": "na mapúlá  ó joka son á loko lá mulato ",
        "ghomla": "gaə̌ bo cə̀ŋ nə́ tám fyə̌ jɔ́yɔ́",
        "bulu": "Ma yi nâ ma lé bivoé bí bɔ́ngó",
        "basaa": "Mɛ̀ gwèe ŋgòŋ i tùk mìntùk mi bitìtiī ndèk.",
    },
    {
        "english": "Dinner time! Spaghetti is my favorite.",
        "french": "L'heure du dîner! Les spaghettis sont mes préférés.",
        "duala": "ó póndá ɗá milɔ́mbí má ɓakálá ndé ná kíyɛ́nɔ́",
        "ghomla": "cwə́ nə́ pfaə́ ywə́.gaə̌ ŋkùŋ mə́nəŋ té'",
        "bulu": "Awɔlɔ ńdíán! miǹsɔ́ŋ miə mǎ nyəə",
        "basaa": "Ŋgɛŋ ì jɛ i kokoa! Yɔ̌m mɛ̀ ŋ́gwês spàgètî.",
    },
    {
        "english": "Bedtime already? But I want to stay up a little longer.",
        "french": "Déjà l’heure du coucher ? Mais je veux rester éveillé un peu plus longtemps.",
        "duala": "pó́ndá ɓenaŋgédí e mápɔ̄ ndé na mapúlá pɛ́tɛ́ ja soná epɛnyɛ́",
        "ghomla": "cwə́ nə́ dǐ.gaə̌ bo ceŋ nə́ cwə́ tə̂ ti té'",
        "bulu": "yə awɔlɔ̌ yā kə óyɔ̄? və dá ma kómbô mɔ́mbô áyǎp",
        "basaa": "Ŋgèdà ì nàŋ ì ŋ̀kɔlà? Ndi mɛ̀ ńsōmbol yên peè inyùu ndèk ǹtèndee i ŋgedà.",
    },
    {
        "english": "Can you read me a bedtime story, please?",
        "french": "Pouvez-vous me lire une histoire avant d'aller au lit, s'il vous plaît ?",
        "duala": "sôn, o ená ó láŋgéá mbá muáŋgó, mɔ̌ ó ɓosó ɓwá ɓenaŋgédí",
        "ghomla": "sesò bo tǎtə́ ta' ywə́ bəm tə dí à?",
        "bulu": "Yə o nə ma lân ńlāŋ ńté bí ngân təkə kə́ bómbo sí? engóngɔ́l",
        "basaa": "Ɓàa ù ńlà sɔŋglɛnɛ mɛ̂ ŋ̀ŋaŋ u nâŋ ɛ̀? Sɔhɔ!",
    },
    {
        "english": "Goodnight, everyone. Sweet dreams!",
        "french": "Bonne nuit tout le monde. Fais de beaux rêves!",
        "duala": "bulú ɓwá ɓwǎḿ ɓato ɓɛ́sɛ̄ naŋgá dɔ́tí á ɓwǎḿ",
        "ghomla": "po tí pəpùŋ wɛ́. Po yɔ̌ mjʉ́m pəpùŋ!",
        "bulu": "Mbamba alú  míā bə́sə, mí yəmə mbamba bíyə́yə̄m",
        "basaa": "Nàŋ ì lam, higlɛ mùt. Bìɛ̌m bìlam!",
    },
    {
        "english": "I hope tomorrow is a great day too.",
        "french": "J'espère que demain sera aussi un bon jour.",
        "duala": "na dúɓɛ́  ná búnyá ɓwá kíɛlɛ ní māyɛ̌ pɛ́  ɓó mɛndɛ́ ɓɛ́ ɓwǎm̀",
        "ghomla": "gaə̌ ŋkwɛ́ gə yo gɔ́ pə tyɛ̌dzʉ̂ pəpùŋ",
        "bulu": "Mə tɔɔ́ aa ndi nâ amosə́ ya akítí fə wê bɔ̌ abə̌ŋ ámǒs",
        "basaa": "Mɛ̀ ḿɓodol lɛ yàni nyɛ̂k à ḿɓā sɔsɔ̄ kɛl.",
    },
    {
        "english": "I'm going to dream about unicorns tonight.",
        "french": "Je vais rêver de licornes ce soir.",
        "duala": "na manaŋgá dɔ́tí á wɔ́si ni ɓɛ́ǹ tɔ́ŋgɔ.yên ebiámu ",
        "ghomla": "gaə̌ gɔ́ nə́ yɔ jʉ̀m nə́ hə̀ŋ wə́",
        "bulu": "ma zu yə̌m licornes bīyə́yə̄m ngoé nyi",
        "basaa": "Mɛ̀ ŋ́ɛ̀mɛl bihɔsì bi bitɔŋ i u ini.",
    },
    {
        "english": "I love my comfy pajamas.",
        "french": "J'adore mon pyjama confortable.",
        "duala": "na tɔ́́ndi mbɔ́tí ám̀ nya iyɔ́ ni e dokamɛ",
        "ghomla": "gaə̌ ŋkùŋ bòŋ dzə̌ lwɔk á",
        "bulu": "ma nyəə éyé jâm ma bómbo aa jə́ sí ",
        "basaa": "Mɛ̀ ŋ́gwēs lɔŋgɛ̂ i mbɔt ì nàŋ yɛ̀m. ",
    },
    {
        "english": "Where's my favorite teddy bear?",
        "french": "Où est mon ours en peluche préféré ?",
        "duala": "mbɔ́ ám̀ nyá loko  ni e ndé ó wɛ́nī",
        "ghomla": "nunus á ye gaə́ ŋkùŋ á yá?",
        "bulu": "éfúmulu ésíŋgi jâm mǎ nyəə é nə vé?",
        "basaa": "Hɛɛ ûrs ì sùt yɛ̀m ì yè?",
    },
    {
        "english": "Did I finish all my homework?",
        "french": "Ai-je fini tous mes devoirs ?",
        "duala": "na ɓɔ́lɛ́ ɓeɓoló ɓám̀ ɓɛ́sɛ̄",
        "ghomla": "gaə̌ myə́ŋ gùŋ mfà' mə?",
        "bulu": "Yə mə́ manəyǎ fɔ́ɔ́ bɔ̌ bīsaé bíam bísə?",
        "basaa": "Ɓàa mɛ̀ m̀mâl yaga minsɔn ŋwɛ̂m ŋwɔmisonā?",
    },
    {
        "english": "Tomorrow is Friday! Weekend, here I come!",
        "french": "Demain c'est vendredi! Week-end, me voilà !",
        "duala": "kiɛlɛ í e ndé ɗónɛsú, sú lá disama ɓá nûn",
        "ghomla": "yǒ bə fradɛ́ ,miŋ gapdzʉ̌ gaə́ yə̌!",
        "bulu": "Akítí ó nə ǹkúl éwongá! amanə́ sɔ́ndo, ma nyí",
        "basaa": "Yàni à yè Ŋgwà Kɔɔ! Màmèlel ma ŋgwà (sɔndî), hâ mɛ̀ ǹlɔ̂!",
    },
    {
        "english": "I need to set my alarm for tomorrow.",
        "french": "Je dois régler mon alarme pour demain.",
        "duala": "na áŋgámɛn ó  tésɛ muséɓá..mwám̀ ónyóló á kíɛlɛ",
        "ghomla": "gɔ̌ nyaptə̀ wâsî à nə́ yó",
        "bulu": "ma yianə komə́ álârm wɔm ású aakítí",
        "basaa": "Mɛ̀ gwèe ŋgòŋ i hek àlârm yɛ̀m inyùu yàni. ",
    },
    {
        "english": "I can't wait to see my friends again.",
        "french": "J'ai hâte de revoir mes amis.",
        "duala": "na e musuŋga ó jɛ́nɛ pɛ́tɛ́ makɔ́m mám̀",
        "ghomla": "gaə̌ bo səŋnyə́ nə́ kwǐ' jɔ msô pə̌",
        "bulu": "Mə nə ojəjaé yā bətá yēn bəmvóé bâm",
        "basaa": "Mɛ̀ ńlà haɓe kî ɓɛ̀mb inyùu ì tɛhɛ̂ lìwanda jɛ̂m.",
    },
    {
        "english": "Did I remember to pack my lunch for tomorrow?",
        "french": "Ai-je pensé à préparer mon déjeuner pour demain ?",
        "duala": "na ɔŋgɛ́lɛ ó ɓóŋsanɛ ɗá lám̀ lá kíɛlɛs",
        "ghomla": "gaə̌ kwɛ̌nyə́ nə́ nɛ́ bvənyə́ shwə̌ á yó lə́?",
        "bulu": "yə ma kə́ símə́sān koməsǎn étyam akak jâm ású akítí?",
        "basaa": "Ɓà mɛ̀ ǹhɔŋɔl lɛ mɛ lamb bìjɛk gwɛ̂m bi kɔsì inyùu yàni?",
    },
    {
        "english": "Time to brush my teeth and go to bed.",
        "french": "Il est temps de me brosser les dents et d'aller me coucher.",
        "duala": "póndá́ ám̀ nyá,sísa masoŋga na wala ó nɔŋgɔ",
        "ghomla": "cwə́ nə́ cǔ' msùŋ nwɔŋ kó",
        "bulu": "awɔlɔ̌ yā sǒb məsǒŋ aa kə́ bómbo sí é kuí yǎ",
        "basaa": "Ŋgèdà ì ŋ̀kɔla lɛ mɛ sogōp, mɛ kɛ i nàŋ.",
    },
    {
        "english": "I wonder what we'll learn in school tomorrow.",
        "french": "Je me demande ce que nous apprendrons à l'école demain.",
        "duala": "na maɓaísɛ́ na mbá mɛ́nɛ́ njé dí mɛ́ndɛnɔ́ jǒkwa ó sukúlu kíɛlɛ",
        "ghomla": "a bò júm á bá' pə̌ gɔ tí lanyə́ sə̀kú yo lə́",
        "bulu": "ma yi mə́ yə̌m yəm jóm bî yée sikólo aakítí",
        "basaa": "Mɛ̀ ḿɓàdɓa i yi i yɔ̌m dì ganigil yani i sùgulù.",
    },
    {
        "english": "Mom, can you tuck me in, please?",
        "french": "Maman, tu peux me border, s'il te plaît ?",
        "duala": "yeyɛ sôn o e ná ó lɛ́lɛ́ mbá",
        "ghomla": "má , bo hwitə̀ á à səso",
        "bulu": "məmá yə o nə ma vɔ́loo, engóngɔ́l?",
        "basaa": "Îni ù ńlà ho mɛ̂, sɔhɔ?",
    },
    {
        "english": "I love my school. It's the best!",
        "french": "J'aime mon école. C'est le meilleur!",
        "duala": "na tɔ́ndi esukúlu ám̀ mɔ́ ndé é ɗɔlí ",
        "ghomla": "gaə̂ ŋkùŋ səkù á.  A bə á pòŋ",
        "bulu": "Ma nyəə sikólo wɔm. Nyə ǎ daŋ!",
        "basaa": "Mɛ̀ ŋ́gwēs sugulù yɛ̀m. Ì yè lòòha ɓàŋga.",
    },
    {
        "english": "I'm grateful for a wonderful day.",
        "french": "Je suis reconnaissant pour cette merveilleuse journée.",
        "duala": "na embea ónyóló a ɓôn búnyá ɓwá ɓwǎm̀",
        "ghomla": "gaə̌ ŋwɛ́nyə̀ nə́ yəŋ tyɛ̌'dzʉ́ gwyə́",
        "bulu": "mə nə məvak ású mbamba amǒs nyi",
        "basaa": "Mɛ̀ ńtī mayègà inyùu ìni kɛl ì lam.",
    },
    {
        "english": "Goodnight, world. See you in the morning!",
        "french": "Bonne nuit, le monde. Je te vois dans la matinée!",
        "duala": "bulú́ ɓwá ɓwǎḿ wásē na mɛ́nɛ́ oá idiɓa ",
        "ghomla": "tí pəpùŋ,so. A cʉ́ a fɔkdzʉ̌!",
        "bulu": "mbamba alú, sí ndon ma yén wɔ̄ mamə́ tyé",
        "basaa": "U ì lam, à ŋ́kɔ̀ŋ u hisi. Dì ńtɛ̄hna bikɛkɛ̀là.",
    },
    {
        "english": "Aced my spelling test!",
        "french": "J'ai réussi mon test d'orthographe !",
        "duala": "na búsi ó kekisɛ lám̀",
        "ghomla": "gaə̂ ghə̀m nə́ ŋwà' wə́",
        "bulu": "ma kə́ kabə̌ məvəələ́ yā ǹtilán",
        "basaa": "Mɛ̀ ǹnɛ̂t kêksɛ̀ yɛ̂m i litìlgà.",
    },
    {
        "english": "Reading is pure magic!",
        "french": "La lecture est une pure magie !",
        "duala": "ɓoláŋgá bwé ndé wámɓwa",
        "ghomla": "nə́ ŋké wə bə a pùŋ",
        "bulu": "ǹláŋán ó nə ngǎŋ",
        "basaa": "Lìsɔŋgɔ̂l li yê ɓàŋga lìkàŋ.",
    },
    {
        "english": "Math puzzles are super fun!",
        "french": "Les énigmes mathématiques sont super amusantes !",
        "duala": "mawómbó má misɔŋgí má mawɔisanɛ",
        "ghomla": "ŋkɛ̌ sɛ́ywə́ ba mà' mtíŋ",
        "bulu": "ayá míńsílí mə̄táŋ mí nə m̀bía fianga",
        "basaa": "Puzzle i minsɔ̀ŋgi i ńnōhla lɛ.",
    },
    {
        "english": "Learning new words daily.",
        "french": "Apprendre de nouveaux mots quotidiennement.",
        "duala": "ókwa lá byala ɓá pényá o búnyá tɛ́",
        "ghomla": "lanyə́ mjɛ̌ghɔm gùŋ tyɛ̌ wɛ́.",
        "bulu": "á yê mim̀fəfe bíbúk amos ósə",
        "basaa": "Yìgîl i biɓuk bi mɔndɔ higī kɛl. ",
    },
    {
        "english": "Science experiments amaze me.",
        "french": "Les expériences scientifiques m'étonnent.",
        "duala": "ŋgany á mbiáko e manyákísánɛ́ mbá",
        "ghomla": "cǐcí mkɛ syaŋsə̀ bo bə́ msyâ",
        "bulu": "ma kátə wók ǹyəmánə́ mam",
        "basaa": "Mìnsɔn mi yi (sìâns) mi ńhēles mɛ̂.",
    },
    {
        "english": "Explorer of history's wonders.",
        "french": "Explorateur des merveilles de l'histoire.",
        "duala": "sôn, o ená ó láŋgéá mbá muáŋgó, mɔ̌ ó ɓosó ɓwá ɓenaŋgédí",
        "ghomla": "mcə́ŋ msyâ cʉ́m tǎtə̀",
        "bulu": "ǹkúli biyəŋ bí mǎm yā mīǹláŋ",
        "basaa": "Ǹtɔŋ màm nû mànyaga ma ŋ́ŋaŋ.",
    },
    {
        "english": "Perfect score in history!",
        "french": "Score parfait dans l'histoire !",
        "duala": "mitila má kɛ́ŋgɛ́ŋgɛ́ má miaŋgó",
        "ghomla": "kedò' pəpu!ŋ nə́ tǎtè",
        "bulu": "mbamba ebom yǎ mīǹláŋ",
        "basaa": "Lòòha mbàgi ì ŋ̀ŋaŋ!",
    },
    {
        "english": "Art class sparks imagination.",
        "french": "Les cours d’art stimulent l’imagination.",
        "duala": "ɓeléédí ɓá ɓolúlí ɓá e mawémsɛ́ mɔŋgɛlɛs",
        "ghomla": "səkú bvə̀ hwǐtə̀ mkɛ̂nyə́",
        "bulu": "ayə́'ə́lə́ ǹkomán bíə́m dá və̄ m̀fasán",
        "basaa": "Yìgîl i likɛŋgɛ li yi i ńyìŋgis mahɔŋɔ̂l.",
    },
    {
        "english": "Writing stories is awesome!",
        "french": "Écrire des histoires, c'est génial !",
        "duala": "tila lá miaŋgó dí tómbísɛ ɗɔlɔ",
        "ghomla": "nə́ nwà' tǎtə̀ ba cyɔ̀",
        "bulu": "ǹtilán míńláŋ ó nə abəŋ",
        "basaa": "Lìtìlà mìŋaŋ li yê lɔŋgɛ̂ lɛ.",
    },
    {
        "english": "Geography is so fascinating.",
        "french": "La géographie est tellement fascinante.",
        "duala": " miaŋgó má mundi má wásē mí tómbi ɓetánysédí",
        "ghomla": "zhografi bá hé' mkɛ̌nyə̀ té'",
        "bulu": "Géographie anə mbə̂ abəŋ",
        "basaa": "Yìgîl i hisī (Gèògrafi) i yê ìlam lɛ. ",
    },
    {
        "english": "Finished my book series!",
        "french": "J'ai fini ma série de livres !",
        "duala": "na máɓɔ̄lɛ lám̀ ɗongo la kálati",
        "ghomla": "gaə̌ myə̀ŋ mcùŋ mwǎ'nyə́ mə́!",
        "bulu": "Mə́ manəyǎ nsámbá bə́ kálatə wɔ̂m",
        "basaa": "Mɛ̀ m̀mâl liɓak jɛ̂m li bikààt!",
    },
    {
        "english": "Solving puzzles feels fantastic.",
        "french": "Résoudre des énigmes est fantastique.",
        "duala": "sɔ lá miano la e ndé manyáká",
        "ghomla": "nə́ ghə̌ dàm jɔ́ ba pòŋ.",
        "bulu": "ə́ bǐ biyalán ású áyáé míńsílí é nə abəŋ",
        "basaa": "Lìtìmbhɛ̀ màŋgèn li ńnɛ̀ lɛ.",
    },
    {
        "english": "Class debate was thrilling!",
        "french": "Le débat en classe était passionnant !",
        "duala": "jaɓanɛ lá byala ó klǎsi dí tá ɓetombisedi",
        "ghomla": "cu'tə̀ ghɔmtə́ kě bòŋ té'",
        "bulu": "ǹjɔ́sán yā ndá sikólo wɔ́ bə́ abəŋ",
        "basaa": "Ŋ̀kwɛ̀l i ndap sùgulù u ye lìyàhgà lɛ.",
    },
    {
        "english": "Mastered the multiplication table.",
        "french": "Maîtriser la table de multiplication.",
        "duala": "bía lá misɔŋgí má kɔisɛ",
        "ghomla": "nə́ kamtə́ cǐ nə ŋkwí' ywə́.",
        "bulu": "ə́ yəm mə̄táŋ yā ákɔk mə́táŋ",
        "basaa": "Yi lìɓam li liɓùlùs lòŋnì ŋ̀ɛm.",
    },
    {
        "english": "Poetry writing is my passion.",
        "french": "L'écriture de poésie est ma passion.",
        "duala": "ɓetilédi ɓá epasi ɓa e ndé mbá ɓélaɓɛ",
        "ghomla": "nə́ ŋwà̀' ywə́ bə yə tsə́ fà'.",
        "bulu": "ma nyəə mə tili ajó nyəán",
        "basaa": "Lìtìlà bìpòɛ̂m li yê jàm mɛ̀ ńlòha gwês.",
    },
    {
        "english": "Science fair first place!",
        "french": "Première place pour l'expo-sciences !",
        "duala": "télɛyɛ lá mbíáko epólo á ɓosó",
        "ghomla": "siaŋs bə́ nə́ dəŋdzə̂ tsʉ̌'",
        "bulu": "bot bə́ osú yǎ ésaē science ",
        "basaa": "Yènɛ i bisu i èkspo sìâŋs.",
    },
    {
        "english": "Musical notes bring joy.",
        "french": "Les notes de musique apportent de la joie.",
        "duala": "mitila má musíkí mí mawáná munyɛŋgɛ",
        "ghomla": "jɛ́ zhwɔ̌pshə́ há ŋwɛ́nyə́.",
        "bulu": "mǎm yā məzík má sɔ̂ aa məvak",
        "basaa": "Màgɛ̂ i ŋ́kòdâ i ńlɔ̀na masee.",
    },
    {
        "english": "Computer coding wizardry achieved!",
        "french": "La magie du codage informatique est réalisée !",
        "duala": "wámɓwa jíŋgea ó.ɓobyédí e sɔɓɛ́",
        "ghomla": "mfá́'tə́ iŋformatik bə pǔ ghə̂",
        "bulu": "ngǎŋ yǎ nsɔlán ínfɔrmatík é bɔban yǎ",
        "basaa": "Lìkàŋ li ńyɛ̀gâ i kɛ̂y-liɓɔk lì ḿɓoŋà",
    },
    {
        "english": "Received a gold star!",
        "french": "J'ai reçu une étoile d'or !",
        "duala": "kasa ŋgéŋgétí a gol",
        "ghomla": "gaə̌ kwǐ msɛ̌ cʉɔ́",
        "bulu": "ma kə́ bi ótétee ó fae",
        "basaa": "Mɛ̀ ŋ̀kôs hyodok hi gôl.",
    },
    {
        "english": "Discovering planets is incredible.",
        "french": "Découvrir des planètes est incroyable.",
        "duala": "sɔ lá́ ....................",
        "ghomla": "nə́ yɔ́ demcà' də̀ŋdzə̌ cʉ́m bə́ msyà",
        "bulu": "ǹsɔmán bə planɛ́t ó nə abəŋ",
        "basaa": "Lìlèbà còdok li ta ɓe jâm li ḿɓòŋà.",
    },
    {
        "english": "Excelled in the spelling bee.",
        "french": "J'ai excellé au concours d'orthographe.",
        "duala": "na wíyɛ ó kekisɛ lá béndá tila ",
        "ghomla": "gaə̌̌ tə́m dəŋdzə̂ nə́ mləŋté nə́ ŋwà' ywə́",
        "bulu": "ma kə́ daŋə́ yə̌m tili",
        "basaa": "Mɛ̀ ŋ̀kɛ̂ haâ i yìgîl i litìlgà.",
    },
    {
        "english": "Finished my art masterpiece!",
        "french": "J'ai terminé mon chef-d'œuvre artistique !",
        "duala": "na máɓɔ̄lɛ musúsú mwám̀ má ɓolúlí",
        "ghomla": "gaə̌ myə̀ŋ ŋwá'nyə́ bvə̌ à",
        "bulu": "mə́ manəyǎ ésaē ńkomán bíə́m jâm",
        "basaa": "Mɛ̀ m̀mâl ńsɔ̄n wɛ̂m i likɛŋgɛ. ",
    },
    {
        "english": "Solved a challenging equation.",
        "french": "Résolu une équation difficile.",
        "duala": "sɔ lá muano mwá musɔŋgí mwá ndutu",
        "ghomla": "nə́ nyáptə́ tá' ywə́ cʉɔ̂tʉɔ̀",
        "bulu": "ə́ yēn éyalán áyaē táŋ",
        "basaa": "Lèbà mbàgi ǹlɛ̀dɛk i ǹsɔ̀ŋgi.",
    },
    {
        "english": "Became class president today!",
        "french": "Devenu président de classe aujourd'hui !",
        "duala": "ɓɛ̂ lá dikóŋgɛ lá klǎsi wɛ́ŋgɛ̄ ",
        "ghomla": "gaə̌ zhi tsədzə̂ dyəsəkú tʉɔ'",
        "bulu": "mə́ tɔ̂ ǹtə́bə osú yǎ ndâ sikólo jam",
        "basaa": "Mɛ̀ ǹyila ŋ́kɛ̀nà (prèzìdâŋ) ndap sùgulù lɛ̀n.",
    },
    {
        "english": "Essay competition winner!",
        "french": "Gagnant du concours de rédaction !",
        "duala": " nú búsí ó kekisɛ lá ɓetilédí ",
        "ghomla": "gaə̌ shyə mlə̀ŋtə́ nə́ ŋwá' ywə́ ",
        "bulu": "mot a kə́ dǎŋ yəmə́ tili",
        "basaa": "Ǹjɛ pèmsan ì ǹtìlà.",
    },
    {
        "english": "Aced the science project!",
        "french": "Réussissez le projet scientifique !",
        "duala": "",
        "ghomla": "nə cyə̌ fà' siaŋsə",
        "bulu": "tókáne ǹsámbá bəyəm mam",
        "basaa": "Nɛ̀da lìɓɔgɔ̂k li ńsɔ̄n i yi (siâŋs).",
    },
    {
        "english": "Geography quiz triumph!",
        "french": "Triomphe du quiz de géographie !",
        "duala": "",
        "ghomla": "ne cyə̌ zhografi",
        "bulu": "miǹsíli yā Géógrafí míá kə́ daŋ",
        "basaa": "Yèmbel ǹtùk-mbâdgà i yi-hisī (gèògràfî).",
    },
    {
        "english": "Creative writing genius unlocked.",
        "french": "Génie de l'écriture créative débloqué.",
        "duala": "",
        "ghomla": "mə̂cwɔ' nə́ ŋwà' ywə́ bə pú lám jɔ́",
        "bulu": "ǹyəmán yā ǹtilán ó yénəban yǎ",
        "basaa": "Yi i litìlà màhɔŋɔ̂l i ŋ́kɔ̂blà.",
    },
    {
        "english": "Stellar performance in drama!",
        "french": "Performance stellaire dans le drame!",
        "duala": "",
        "ghomla": "fà' pəpùŋ nə́ nwə̌ cwə̂pùŋ",
        "bulu": "ǹdanán ə́ mǎm bivəəla",
        "basaa": "Lìɓɔ̀ŋɔ̀k lìkɛŋi li ŋgìi i kède bìkùù.",
    },
    {
        "english": "Got a perfect attendance award.",
        "french": "J'ai obtenu un prix d'assiduité parfaite.",
        "duala": "",
        "ghomla": "gaə̃̌ ghə ŋkədó' fà' tə̂ yá'",
        "bulu": "ma kə́ bi āfə̄p amú ma sɔ́ eyɔŋ ésə",
        "basaa": "Mɛ̀ ŋ̀kôhna mbogī ì lìɓa ì hèli.",
    },
    {
        "english": "Science Olympiad champion!",
        "french": "Champion de l'Olympiade des sciences !",
        "duala": "",
        "ghomla": "dəŋdzə̌ nə́ jyé gùŋ mtsʉ'",
        "bulu": "ə́ mot ǎ daŋ yəmə́ mam mə́sə",
        "basaa": "Ǹyèmbèl pèmsan ì kɛŋi i yi (sìâŋs).",
    },
    {
        "english": "Learning languages is exciting.",
        "french": "Apprendre les langues est passionnant.",
        "duala": "",
        "ghomla": "mə̂cwɔ' nə́ ŋwà' ywə́ bə pú lám jɔ́",
        "bulu": "ǹyéán miǹkɔ́bo ó nə mbamba jam",
        "basaa": "Yìgîl i mahɔp i ye nyàmndà.",
    },
    {
        "english": "Stellar performance in music!",
        "french": "Performance stellaire en musique!",
        "duala": "",
        "ghomla": "gɛ̌ zhwɔ̌pshyə́ pəpùŋ",
        "bulu": "ewólō ńyēm məzík ",
        "basaa": "Lìɓɔ̀ŋɔ̀k lìkɛŋi li ŋgiî i kède ŋ̀kòdâ. ",
    },
    {
        "english": "best athlete of the month!",
        "french": "meilleur athlète du mois !",
        "duala": "",
        "ghomla": "dəŋdzə̌ jyé dʉ̌ nə́ ŋwə́",
        "bulu": "ə́ mot ǎ daŋ bə atlɛ́t bə́sə yǎ ngɔn",
        "basaa": "Mùt màkwasi nû kɛŋi nû soŋ.",
    },
    {
        "english": "Book club president elected.",
        "french": "Président du club de lecture élu.",
        "duala": "",
        "ghomla": "tsədzə̌ cùtə́ nké ywə̌",
        "bulu": "ǹjô emɔɔ  bot bá láŋ a kə́ tɔ́pban",
        "basaa": "Ɓa ńtɛ̄p i ŋ́kɛ̀nà ǹtoŋ u bikààt.",
    },
    {
        "english": "Invented something amazing today.",
        "french": "J'ai inventé quelque chose d'incroyable aujourd'hui.",
        "duala": "",
        "ghomla": "gaə̌ té ywə́ msyǎ tʉɔ̌.",
        "bulu": "ma kə́ tē jóm bot bə́sə bá kám də́n",
        "basaa": "Hɛ̌k ŋgìm yɔ̌m i helha lɛ̀n.",
    },
    {
        "english": "Highest score in the class!",
        "french": "Meilleur score de la classe !",
        "duala": "",
        "ghomla": "məcwə̌' dyə̌ sə̀kú ",
        "bulu": "ébom yá lot bibom bísə ábā sikólo",
        "basaa": "Sɔsɔ̄ mbàgi i kède ndap sùgulù.",
    },
    {
        "english": "Participated in a debate.",
        "french": "Participation à un débat.",
        "duala": "",
        "ghomla": "nə́ kò cu'tə́",
        "bulu": "ǹnyɔŋán ngap ə́ débá",
        "basaa": "Lìɓa i kède ŋ̀kwɛ̀l u yi.",
    },
    {
        "english": "Solved a tricky riddle!",
        "french": "J'ai résolu une énigme délicate !",
        "duala": "",
        "ghomla": "nə́ fà' fà' cyɔ̌cyɔ̂.",
        "bulu": "mə́ yalan yǎ ayāé ńsílí",
        "basaa": "Mɛ̀ ǹleba dimbhɛ̀ ì ŋgèni.",
    },
    {
        "english": "Mastered the piano recital.",
        "french": "Maîtriser le récital de piano.",
        "duala": "",
        "ghomla": "nə  kǎmtə́ ŋkɛ̂ ywə́",
        "bulu": "ayəmə́ áfə̄p yā mbomán éǹgɔmbé",
        "basaa": "Yi rèsìtâl lòŋnì ŋ̀ɛm.",
    },
    {
        "english": "Learned a new dance!",
        "french": "J'ai appris une nouvelle danse !",
        "duala": "",
        "ghomla": "nə́ lanyə́ nə̀ŋ sə̌ ",
        "bulu": "ma kə́ yê m̀fefe ábók",
        "basaa": "Nigîl lìlɔk li yɔndɔ.",
    },
    {
        "english": "Published my first poem.",
        "french": "J'ai publié mon premier poème.",
        "duala": "",
        "ghomla": "gaə̌̌ cyǎnyə́ də̂ŋdzə̌ ŋwǎnyə́ á.",
        "bulu": "ma kə́ kúli ńtilán ósú wɔ̂m",
        "basaa": "Mɛ̀ m̀ɓamb poɛ̂m yɛ̀m ì bisu.",
    },
    {
        "english": "Quiz bowl champion title!",
        "french": "Titre de champion de quiz bowl !",
        "duala": "",
        "ghomla": "tsǒ məcwɔ̌' nə́ kwis bɔl ",
        "bulu": "dzóé nâ mot ǎ daŋ yalǎn mīǹsílí",
        "basaa": "Jǒl li ńsɔ̄n li ńyèmbèl ǹtùk-mbâdgà.",
    },
    {
        "english": "Identified rare species today.",
        "french": "Espèce rare identifiée aujourd'hui.",
        "duala": "",
        "ghomla": "gaə̌ bə̰́ məcwɔ' né kwǐ boks",
        "bulu": "bá kē yēn ayáé bíyə́m də́n",
        "basaa": "Mɛ̀ ǹyi bihègel bî bi ńtòl ɓee lɛ̀n.",
    },
    {
        "english": "Earned my pen license!",
        "french": "J'ai obtenu mon permis de plume !",
        "duala": "",
        "ghomla": "məcǐ ywə́ bə mò lám jɔ́ tʉɔ̌'",
        "bulu": "mə́ bi yǎ afə́p yā vɔ́lo nâ mə́ dutu",
        "basaa": "Mɛ̀ ŋ̀kôs kundɛ̀ yɛ̀m ì sao.",
    },
    {
        "english": "Recited a famous speech.",
        "french": "A récité un discours célèbre.",
        "duala": "",
        "ghomla": "gaə̌ ghə́ pipà nə ŋwà' ywə̌",
        "bulu": "a kə kɔ́bo mbamba ǹkɔ́bo",
        "basaa": "Mɛ̀ ǹti ŋgûy ŋ̀kwɛ̀l.",
    },
    {
        "english": "Successfully completed science experiment.",
        "french": "Expérience scientifique terminée avec succès.",
        "duala": "",
        "ghomla": "nə́ ghɔm mghɔ̀m bə̌ pu jyə́",
        "bulu": "ayéé mimfefe mí mam é tóé yǎ",
        "basaa": "Ǹsɔn u yi u ḿmâl lôŋnì lìnɛ̀t.",
    },
    {
        "english": "Art showcase participant!",
        "french": "Participant à la vitrine artistique !",
        "duala": "",
        "ghomla": "nə́ lanyə́́ fà' mí pəpuŋ",
        "bulu": "a nyɔŋə ngap ńlītán mītyə́tyə́ŋ bəkom bíə́m",
        "basaa": "M̀ɓàŋ i teblè i leman i likɛŋgɛ.",
    },
    {
        "english": "Perfect attendance all month!",
        "french": "Une fréquentation parfaite tout le mois !",
        "duala": "",
        "ghomla": "nə́ hwǐtə né mfà' bvə",
        "bulu": "mbamba ǹyəmbanə́ ǹgúmbā ngɔn",
        "basaa": "Lìyuugà li helī higlɛ soŋ.",
    },
    {
        "english": "Won the chess championship!",
        "french": "A remporté le championnat d'échecs !",
        "duala": "",
        "ghomla": "mkǎnyé pəpùŋ nə́ yeŋ ŋwə́",
        "bulu": "a kə bi məsə́ŋgán bá ku",
        "basaa": "À ǹjɛ pêmsan ì sɔ̀ŋgɔ-bìkaasà",
    },
    {
        "english": "Good morning, time to work!",
        "french": "Bonjour, il est temps de travailler !",
        "duala": "",
        "ghomla": "o tí lə, tàm nə́ fà'!",
        "bulu": "mbamba tyé, awɔlɔ ésáé é kuí yǎ",
        "basaa": "Mɛ̀ ǹyegà (à/ɓee), ŋgèdà ì ɓòlo ì ŋ̀kɔlà.",
    },
    {
        "english": "Have a productive day!",
        "french": "Passez une journée productive !",
        "duala": "",
        "ghomla": "tyɛ̌dzʉ̂ pəpùŋ ",
        "bulu": "lotáne amǒs ó bīlí abuí bibumá",
        "basaa": "Kɛl yɔ̂ŋ i ǹnum matam!",
    },
    {
        "english": "I love my job.",
        "french": "J'adore mon travail.",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ fà' tsaə̀.",
        "bulu": "ma nyəə ésaé jâm",
        "basaa": "Mɛ̀ ŋ́gwēs ɓolo yɛ̂m.",
    },
    {
        "english": "Lunch break, yum!",
        "french": "Pause déjeuner, miam !",
        "duala": "",
        "ghomla": "hwǐtə nə́ bvə̀nyə́ shwə̂!",
        "bulu": "awɔ̌n étyam akak, miam!",
        "basaa": "Nɔ̀yɛ̀ i jɛ, halà ni!",
    },
    {
        "english": "Meetings are fun.",
        "french": "Les réunions sont amusantes.",
        "duala": "",
        "ghomla": "mcu'tə́ ba ŋwɛ̌nyə̀ .",
        "bulu": "bikúán bíá wɔle",
        "basaa": "Bìɓɔ̀ma bi nòhlà.",
    },
    {
        "english": "Learning new skills today.",
        "french": "Apprendre de nouvelles compétences aujourd’hui.",
        "duala": "",
        "ghomla": "pə lǎnyə ywə̌ sə́ tʉɔ̌'. ",
        "bulu": "ə́ yê mbamba bə́ mam də́n",
        "basaa": "Yìgîl i maɓɔ̀ŋɔ̀k ma mɔndɔ.",
    },
    {
        "english": "Let's solve problems together.",
        "french": "Résolvons les problèmes ensemble.",
        "duala": "",
        "ghomla": "pə  pə́mtə́ dyɛ̌' mnwə̀.",
        "bulu": "ńkománe məjó ǹsámbá",
        "basaa": "Di saŋgâl mìndaŋ ǹtoŋ.",
    },
    {
        "english": "Teamwork makes us strong.",
        "french": "Le travail d’équipe nous rend forts.",
        "duala": "",
        "ghomla": "nə́ pə́mtə́ fà' yá ghʉ̌'.",
        "bulu": "ésaé ábuǐ bot yá və̄ bía ngul",
        "basaa": "Ɓòlo i yûm i ńtī ɓes ŋgùy.",
    },
    {
        "english": "Can I help you?",
        "french": "Puis-je vous aider?",
        "duala": "",
        "ghomla": "bə kwǐtə̀ ó á?",
        "bulu": "yə mə nə mía vɔ́lo?",
        "basaa": "Ɓàa mɛ̀ ńlà hola wɛ̂?",
    },
    {
        "english": "Time for a coffee break!",
        "french": "C'est l'heure d'une pause café !",
        "duala": "",
        "ghomla": "tàm nə́ nwə́ kafɛ̌!",
        "bulu": "awɔlɔ áwɔ̌n kɔ̄fí é kuí yǎ",
        "basaa": "Ŋgɛŋ lìnyɔ kɔ̀fi ì ŋ̀kɔlà",
    },
    {
        "english": "Feeling accomplished, hooray!",
        "french": "Se sentir accompli, hourra !",
        "duala": "",
        "ghomla": "hm gaə̌ da' myə̀ŋ!",
        "bulu": "məvak amú ésaē é man yǎ",
        "basaa": "Lɛ mɛ ńnōgda lɛ mɛ̀ ǹyonos mâm. Halà ni!",
    },
    {
        "english": "Happy to be here.",
        "french": "Heureux d'être ici.",
        "duala": "",
        "ghomla": "gaə̌̌ ŋwɛ̌nyə̀ nə́ pə tsɔ̀'",
        "bulu": "məvak amú mə̄ nə́ va",
        "basaa": "Mɛ̀ ŋ́kɔ̀n masee lɛ mɛ̀ yè hina!",
    },
    {
        "english": "I enjoy my tasks.",
        "french": "J'apprécie mes tâches.",
        "duala": "",
        "ghomla": "gaə̌ ŋkù̀ŋ fà' tsaə̀.",
        "bulu": "ma nyəə bisáé bíam",
        "basaa": "Mɛ̀ ŋ́gwēs biɓòlo gwɛ̂m.",
    },
    {
        "english": "Smiles make work better.",
        "french": "Les sourires améliorent le travail.",
        "duala": "",
        "ghomla": "wî ghə fà' ghɔ̌ dzə̀",
        "bulu": "loe wɔ́ tyénde esáé",
        "basaa": "Ŋwɛ̀mlà i ńhòyos ɓolò.",
    },
    {
        "english": "Teammates are like family.",
        "french": "Les coéquipiers sont comme une famille.",
        "duala": "",
        "ghomla": "msò fà' bə́ bà' tá' tuŋdyə̌.",
        "bulu": "bəmvóé bə́ nə anə́ ndá bot",
        "basaa": "Màwanda ma yûm i ɓolō mà yê kìkìi ndap ɓòt.",
    },
    {
        "english": "Time for a quick chat.",
        "french": "Il est temps de discuter rapidement.",
        "duala": "",
        "ghomla": "tàm nə́ də gwʉ̌' sà'",
        "bulu": "eyɔ̌ŋ yā lân ávól é kuí yǎ",
        "basaa": "Ŋgèdà ì ŋ̀kɔla lɛ di kwɛl ndèk.",
    },
    {
        "english": "I finished my project!",
        "french": "J'ai fini mon projet !",
        "duala": "",
        "ghomla": "gaə̌  myəŋ mfà' mə̂",
        "bulu": "mə́ manəyǎ ńsóŋán wɔ̂m",
        "basaa": "Mɛ̀ m̀mâl ḿɓɔgɔ̂k ńsɔ̄n wɛ̂m.",
    },
    {
        "english": "Excited for tomorrow's challenges.",
        "french": "Enthousiasmé par les défis de demain.",
        "duala": "",
        "ghomla": "e bo səŋnyè nə́ mkəlò' fɔ̂kdzʉ̌",
        "bulu": "ojəjae amú mǎm yā aakití",
        "basaa": "Mɛ̀ ńyàmnda inyùu màm ma yani nû à ńlɔ̀.",
    },
    {
        "english": "Celebrating a successful day!",
        "french": "Célébrer une journée réussie !",
        "duala": "",
        "ghomla": "ně bo cwɔ̌' ,cà' nə mfà' pəpùŋ tʉɔ̌' !",
        "bulu": "ə́ vak amú mbamba amǒs",
        "basaa": "Di see inyùu kɛl màm ma ńyɔ̂n.",
    },
    {
        "english": "Goodbye, see you tomorrow.",
        "french": "Au revoir à demain.",
        "duala": "",
        "ghomla": "oo; tə yó.",
        "bulu": "bíálə̄ á tɔ̂ aakítí",
        "basaa": "Òǒ, dì ńtɛ̄hɛna yani.",
    },
    {
        "english": "Learning from mistakes is okay.",
        "french": "Apprendre de ses erreurs, c’est bien.",
        "duala": "",
        "ghomla": "nə́ piŋ mhɔ̌ ba pùŋ.",
        "bulu": "ə́ yê bivus étē, anə mbamba jam",
        "basaa": "Yìgîl nì njɛ̌l dìhòhà i yê lɔŋgɛ̂.",
    },
    {
        "english": "My boss is awesome.",
        "french": "Mon patron est génial.",
        "duala": "",
        "ghomla": "tá fà' á be ghǎmtə́ .",
        "bulu": "mása wɔm anə ǹnyəán",
        "basaa": "Kiŋɛ̂ yɛ̀m ì ɓòlo ì yè lɔŋgɛ̂.",
    },
    {
        "english": "Thankful for this opportunity.",
        "french": "Merci pour cette opportunité.",
        "duala": "",
        "ghomla": "gaə̌ ghò'tə́ yəŋ sɔ̂.",
        "bulu": "akíba amú maa nyí",
        "basaa": "Mɛ̀ ǹyega inyùu nɛhɛp i likòga.",
    },
    {
        "english": "Time to head home.",
        "french": "Il est temps de rentrer à la maison.",
        "duala": "",
        "ghomla": "yə̀ŋ tàm nə́ bhənyə́ dyə̌.",
        "bulu": "eyɔ̌ŋ yā búlan ndá é kuí yǎ",
        "basaa": "Ŋgèdà ì ŋ̀kɔla lɛ mɛ huu i ndap.",
    },
    {
        "english": "Dinner with my loved ones.",
        "french": "Dîner avec mes proches.",
        "duala": "",
        "ghomla": "tsʉ̌ ywə́ pwa mfə̌ pə̂",
        "bulu": "ə́ bɔ étyam akak aa bəmvóé",
        "basaa": "Jɛ i kòkoa nì ɓòt ɓɛ̂m ɓa ndap.",
    },
    {
        "english": "Sharing stories with family.",
        "french": "Partager des histoires en famille.",
        "duala": "",
        "ghomla": "tǎtə tsə̌ tùŋdyə̂",
        "bulu": "ə́ kabǎn miǹláŋ ə́ ndâ bot",
        "basaa": "Lìaŋâl mìŋaŋ i kède ndap ɓòt.",
    },
    {
        "english": "Helping with chores.",
        "french": "Aider aux tâches ménagères.",
        "duala": "",
        "ghomla": "hwǐ̂tə́ mfà' dyə̌.",
        "bulu": "ə́ vɔ́lo ású bīsaé yā ndá",
        "basaa": "Holâ i sal bìɓòlo bi ndap.",
    },
    {
        "english": "Bedtime stories are special.",
        "french": "Les histoires au coucher sont spéciales.",
        "duala": "",
        "ghomla": "tǎtə tsʉ́' ba hyə́ cǐ",
        "bulu": "miǹláŋ yā éyɔŋ bá bómbo sí mí nə avál āfə́",
        "basaa": "Ŋgèdà inyùu mìŋaŋ mi nâŋ ì yè ǹsɛŋg lɛ.",
    },
    {
        "english": "Grateful for a good day.",
        "french": "Reconnaissant pour une bonne journée.",
        "duala": "",
        "ghomla": "motokwà nə́ yəŋ tyɛ̌'dzù.",
        "bulu": "məvak ású mbamba amǒs",
        "basaa": "Màyègà inyùu kɛl ì lam.",
    },
    {
        "english": "Dreaming of tomorrow's adventures.",
        "french": "Rêver des aventures de demain.",
        "duala": "",
        "ghomla": "tí jʉ̀m nə́ mfà' fɔ̌kdzʉ̌.",
        "bulu": "ə́ yə̌m bīyə́yə̄m ású mǎm yā aakítí",
        "basaa": "Ɛ̀mɛ̀l màm ù ǹlama ɓɔ̂ŋ yani.",
    },
    {
        "english": "Ready for a good night's sleep.",
        "french": "Prêt pour une bonne nuit de sommeil.",
        "duala": "",
        "ghomla": "bə dí pəpùŋ cwəlɔ̌.",
        "bulu": "ǹkoməsán ású abəŋ álú óyɔ́",
        "basaa": "Mɛ̀ tee lɛ mɛ̀ ńnàŋal lɔŋgɛ̂ nì u ini.",
    },
    {
        "english": " I can't wait tomorrow.",
        "french": "Je ne peux pas attendre demain.",
        "duala": "",
        "ghomla": "pə́ də́ pyáp yó.",
        "bulu": "mə̌ vɔ̌ ki yaŋgə aakítí",
        "basaa": "Mɛ̀ ńlà ɓe mɛ̂ ɓɛ̀mb yani.",
    },
    {
        "english": "Family time is precious.",
        "french": "Le temps en famille est précieux.",
        "duala": "",
        "ghomla": "tàm cʉ́m tùŋdyə̌ bá tʉɔ̌də̀ŋ.",
        "bulu": "eyɔ̌ŋ yā lot aa ndá bot é nə m̀fí",
        "basaa": "Ŋgèdà i ɓa lòŋnì ɓòt ɓɔŋ ɓa ndap ì yè ǹsɛŋg lɛ.",
    },
    {
        "english": "Proud of my achievements.",
        "french": "Fier de mes réalisations.",
        "duala": "",
        "ghomla": "gaə̌ ŋwɛnyə̀ nə́ fà' tsaə̌.",
        "bulu": "mintak amú mimbɔ̌n míam",
        "basaa": "Màsee inyùu màm mɛ̀ m̀ɓɔ̂ŋ.",
    },
    {
        "english": "Work hard, play harder!",
        "french": "Travaillez dur, jouez plus fort !",
        "duala": "",
        "ghomla": "kaktʉɔ́; fyə́ pepùŋ!",
        "bulu": "sááne abuí, vueáne abuí",
        "basaa": "Sala ŋgàndàk, tùga nì ŋgàndàk ŋgùy.",
    },
    {
        "english": "Being kind at work matters.",
        "french": "Être gentil au travail est important.",
        "duala": "",
        "ghomla": "nə ŋwɛnyə fà' bá hwitə́.",
        "bulu": "mbamba fúlú a vɔ́lo ésaē",
        "basaa": "Lɔŋgɛ̂ i liɓâk i ɓòlo i yê ǹsɛŋg lɛ.",
    },
    {
        "english": "Learning and growing daily.",
        "french": "Apprendre et grandir au quotidien.",
        "duala": "",
        "ghomla": "lanyə́ fà' nə́ kwyə̀.",
        "bulu": "ə́ yê aa yáé eyɔŋ ésə",
        "basaa": "Nigîl ni hɔl higlɛ kɛl.",
    },
    {
        "english": "Challenges make us strong.",
        "french": "Les défis nous rendent forts.",
        "duala": "",
        "ghomla": "mtsənyə́ ghə́ mò kwyə́.",
        "bulu": "məsə́ŋgán má və̄ m̀fefě ngul",
        "basaa": "Màm ma ńlɛ̀t ma ńyìlis ɓes ɓòt ɓa ŋgûy.",
    },
    {
        "english": "Excited for the weekend!",
        "french": "Hâte pour le week-end !",
        "duala": "",
        "ghomla": "səsə̀ŋ nə́ myə́ŋ gâpdzʉ̌.",
        "bulu": "bɔ̌ ávōl ású ámanə́ sɔ́ndo",
        "basaa": "Mɛ̀ ńyàmnda inyùu lìsuk li sɔndî.",
    },
    {
        "english": "Reflecting on the day.",
        "french": "Réflexion sur la journée.",
        "duala": "",
        "ghomla": "sɛnyə́ nə́ tyɛ̌dzʉ̌.",
        "bulu": "m̀fasán ásū ámǒs",
        "basaa": "Pèk inyùu kɛl.",
    },
    {
        "english": "Tomorrow is a new day.",
        "french": "Demain est un autre jour.",
        "duala": "",
        "ghomla": "yó bə mú' tyɛ̌'dzʉ̂",
        "bulu": "aakítí ó nə amǒs ōfə́",
        "basaa": "Yàni à yè kɛl yɔ̀ndɔ.",
    },
    {
        "english": "Cherishing happy moments.",
        "french": "Chérir les moments heureux.",
        "duala": "",
        "ghomla": "ŋwɛ̌nyə́ nə cwə̀ pəpùŋ",
        "bulu": "nyəŋələ̌ biyɔŋ məvak",
        "basaa": "Sìŋgɛ̀ màŋgèdà ma masee.",
    },
    {
        "english": "Work-life balance is important.",
        "french": "L’équilibre travail-vie personnelle est important.",
        "duala": "",
        "ghomla": "nə ghə bakələ̀ nə́ tám ba pùŋ.",
        "bulu": "ǹsóán ésáé aa enyiŋ é nə m̀fí",
        "basaa": "Kɔ̀là i polâ ɓòlo nì nìŋ i mût i yê ǹsɛŋg lɛ.",
    },
    {
        "english": "Time for a bedtime hug.",
        "french": "Il est temps de faire un câlin au coucher.",
        "duala": "",
        "ghomla": "tàm nə dà'nyə́ tə́ nwɔ́ŋ kó",
        "bulu": "eyɔ̌ŋ yā nyəŋələ ḿbōmbánə́ sí é kuí yǎ",
        "basaa": "Ŋgèdà ì ŋ̀kɔla inyùu lìsɔs màmaŋ i kɛ̀ i nàŋ.",
    },
    {
        "english": "I love my bedtime routine.",
        "french": "J'adore ma routine du coucher.",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ nə́ nwɔ̀ŋ kó gùŋ tyɛ̌' wɛ́.",
        "bulu": "ma nyəə mam mâm yā mbómbánə́ sí",
        "basaa": "Mɛ̀ ŋ́gwēs liɓɔgɔ̂k jɛ̂m li ŋgɛŋ hìlɔ.",
    },
    {
        "english": "Sleep tight, sweet dreams.",
        "french": "Dors bien, fais de beaux rêves.",
        "duala": "",
        "ghomla": "tí pəpùŋ , yɔ́ mzhʉ́m pəpùŋ",
        "bulu": "bómbo mvɔ'é o yəm abəŋ bíyə̄yə̄m",
        "basaa": "Nàŋ ì lam,bìɛ̌m bìlam.",
    },
    {
        "english": "Gratitude for a great day.",
        "french": "Gratitude pour cette belle journée.",
        "duala": "",
        "ghomla": "motokwà nə́ yəŋ tyɛ̌'dzù.",
        "bulu": "akə́va amú mbamba amǒs nyi",
        "basaa": "Màyègà inyùu ìni sɔsɔ̄ kɛl.",
    },
    {
        "english": "Ready for tomorrow's adventures.",
        "french": "Prêt pour les aventures de demain.",
        "duala": "",
        "ghomla": "bə fà' mfà' yó.",
        "bulu": "ǹkomesán ásū mǎm yā aakítí",
        "basaa": "Mɛ̀ tee inyùu màm mɛ̀ ḿɓɔ̀ŋ yani.",
    },
    {
        "english": "Thankful for my job.",
        "french": "Merci pour mon travail.",
        "duala": "",
        "ghomla": "matokwa nə́ yən fà'.",
        "bulu": "akíba amú ésaē jâm",
        "basaa": "Mɛ̀ ǹyega  ŋgandàk inyùu ɓòlo yɛ̂m.",
    },
    {
        "english": "I enjoy every moment.",
        "french": "J'apprécie chaque instant.",
        "duala": "",
        "ghomla": "gaə̌ bo də̂ tàm.",
        "bulu": "ma nyəə éyɔŋ ésə",
        "basaa": "Mɛ̀ ńsee i maŋgèdà mɔmasô.",
    },
    {
        "english": "Morning hustle begins now!",
        "french": "L'agitation matinale commence maintenant !",
        "duala": "",
        "ghomla": "nwə́ fɔ̌kdzʉ̌ tò' cwə̂lɔ̌",
        "bulu": "odídî yā mām mə́tyé wɔ́ kâ də́n",
        "basaa": "Hògdà i bikɛkɛ̀là ì ḿɓòdol nânɔ.",
    },
    {
        "english": "Day of endless possibilities!",
        "french": "Journée de possibilités infinies !",
        "duala": "",
        "ghomla": "cící mə̂jə̂ nə́ yəŋ tyɛ̌'dzû",
        "bulu": "amosə́ bə ábuí bə mâ",
        "basaa": "Kɛl màm ma ńlà ɓoŋà ma ḿmàl ɓee.",
    },
    {
        "english": "Passion drives my work.",
        "french": "La passion anime mon travail.",
        "duala": "",
        "ghomla": "grúə' nə- míŋ fà' tsaə̌",
        "bulu": "ǹyəán wɔ́ və̄ ma ngul ésaē jâm",
        "basaa": "Màkend ma gwehâ ma ńyemēs ɓòlo yɛ̂m.",
    },
    {
        "english": "Lunch break, fueling success!",
        "french": "La pause déjeuner, moteur du succès !",
        "duala": "",
        "ghomla": "hwǐtə́ nə́ bvənyə́ shwə̀ , gàk fà' pəpùŋ",
        "bulu": "awɔ̌n étyam akak, éngin ǹdaŋán",
        "basaa": "Nɔ̀yɛ̀ i jɛ, kɛ̀y (mòtɛ̂r) i liyonôs màm.",
    },
    {
        "english": "Strategic meetings fuel growth.",
        "french": "Les réunions stratégiques alimentent la croissance.",
        "duala": "",
        "ghomla": "cu'tə̀ pə́pùŋ ghə fà' ghɔ̌ dzə́",
        "bulu": "mbamba bíkuán bíá sɔ́ aa məyáé ",
        "basaa": "Bìɓɔma bi pêk bi ńjēs mahɔ̂l.",
    },
    {
        "english": "Constantly learning, always evolving.",
        "french": "Apprendre constamment, toujours évoluer.",
        "duala": "",
        "ghomla": "nə́ cwə bə danyə ghə mo' kwyə́",
        "bulu": "ə́ yê eyɔŋ ésə, ə́ kə ósū",
        "basaa": "Nigil hiŋgɛ̄ŋ, kɛ̀ i bisu yòha nì kɛl.",
    },
    {
        "english": "Solving challenges, rising higher.",
        "french": "Résoudre les défis, monter plus haut.",
        "duala": "",
        "ghomla": "nə́ cyɔ̂ mkəlo' ghə́ mo lo'nyə́ gwiŋ",
        "bulu": "ǹkomán mə̄sóŋgán, və kə ósū",
        "basaa": "Lìlèbà jɛ̌l i pam mìŋkàgdà mi mâm, li ŋ́kɛ̀na wɛ̂ hàà i ŋgìi.",
    },
    {
        "english": "Team synergy powers success.",
        "french": "La synergie d’équipe est le moteur du succès.",
        "duala": "",
        "ghomla": "nə́ pèmtə́ fà' bə̌ gàk fà' pəpùŋ",
        "bulu": "mfulanə̂ wɔ́ ésáé a sɔ́ aa məyáé ",
        "basaa": "Màholnà ma yûm mɔn ma ńtī mbagī ì lam.",
    },
    {
        "english": "How may I contribute?",
        "french": "Comment puis-je contribuer ?",
        "duala": "",
        "ghomla": "bə̌ hwǐtə̀ m kə́?",
        "bulu": "mə nə bɔ áyá ású nâ mə́ bɔ jóm eziŋ?",
        "basaa": "Lɛlaa mɛ̀ ńlà holâ?",
    },
    {
        "english": "Quick coffee for energy!",
        "french": "Un café rapide pour de l'énergie !",
        "duala": "",
        "ghomla": "do'nyə́ kafɛ́ nə́ kwǐ'  grúə",
        "bulu": "kɔfí avól avól ású ngul",
        "basaa": "Hɔɔ ɓɔ̀ŋ mɛ̂ kɔ̀fi inyùu ì yɔ̀ŋ ŋgùy.",
    },
    {
        "english": "Achieving goals, celebrate briefly!",
        "french": "Atteindre les objectifs, célébrez brièvement !",
        "duala": "",
        "ghomla": "nə́ míŋ fà' ghə̌ mò ná' ŋwɛ̌nyə̀",
        "bulu": "ə́ toē mīǹsóŋán, fonáne abuí",
        "basaa": "Yonos màɓɔgɔ̂k, ndi see ndèk.",
    },
    {
        "english": "Entrepreneurial spirit fuels me.",
        "french": "L'esprit d'entreprise m'anime.",
        "duala": "",
        "ghomla": "nə pəmtə̀ fà' cʉ́m ŋkwɛ̂nyə́ a.",
        "bulu": "ǹsísim mińdzə́ŋán ó nə ma nyól",
        "basaa": "Mbuu i ɓolō i ɓôt i yê mɛ̀ i kède.",
    },
    {
        "english": "Tasks align with my vision.",
        "french": "Les tâches correspondent à ma vision.",
        "duala": "",
        "ghomla": "mfà' wə̌ bəmtə́ nə́ mkwɛnyə́",
        "bulu": "bisáé bíá yian aa miǹsóŋán míam",
        "basaa": "Mìnsɔn mi koli lòŋnì lìtɛhgɛ̀ jɛ̂m.",
    },
    {
        "english": "Smiles propel business forward.",
        "french": "Les sourires font avancer les affaires.",
        "duala": "",
        "ghomla": "wî ghə fà' ghɔ̌ dzə̀",
        "bulu": "məvak má vɔ́lo nâ mam mə́ kə ósū",
        "basaa": "Ŋwɛ̀mlà i ńkɛ̀na likɔ̀t ŋ̀kùs nì bìsu.",
    },
    {
        "english": "Teammates, key business partners.",
        "french": "Coéquipiers, partenaires commerciaux clés.",
        "duala": "",
        "ghomla": "mghɛ̌ fà', msô fà', mtɛ̌ sim cyɔ̌",
        "bulu": "bəmvóé, bə vɔ́lo bá yian",
        "basaa": "Màwanda ma ɓolo, hìlìbà inyùu màwanda ma likɔ̀t ŋkùs.",
    },
    {
        "english": "Quick strategy chat, always beneficial.",
        "french": "Chat stratégique rapide, toujours bénéfique.",
        "duala": "",
        "ghomla": "mə̂jə̂ nə́ do'nyə́ ghə̌ pê",
        "bulu": "ojəjae ésīŋgi fəg, já vɔ́lo éyɔŋ ésə",
        "basaa": "Lìkɛŋgɛ li ŋ́kwɛ̀l i ńhɔɔ, li ye ndigî ǹsɛŋg.",
    },
    {
        "english": "Completed another milestone!",
        "french": "Une autre étape franchie !",
        "duala": "",
        "ghomla": "mù' fà' mímí",
        "bulu": "bí daŋ yǎ ḿfefe étáp",
        "basaa": "Lìtuŋga lìpɛ li dì ǹtagɓɛ̀",
    },
    {
        "english": "Tomorrow's challenges, bring it!",
        "french": "Les défis de demain, apportez-les !",
        "duala": "",
        "ghomla": "po lə̌ mkəlò' yó sɔ̌'",
        "bulu": "miǹsóŋán yā aakít́ zaáne aa míə́",
        "basaa": "Mìŋkàgdà mi mâm mi yani, lɔ̀na mɔ!",
    },
    {
        "english": "Cheers to a successful day!",
        "french": "Bravo pour cette journée réussie !",
        "duala": "",
        "ghomla": "pà'lə́ nə́ yəŋ tyɛ̌'dzû pəpùŋ",
        "bulu": "atyə́ŋ amú məkabə yǎ mōs wu",
        "basaa": "Lɔŋgɛ i jâm lɛ kɛl ì ǹlama.",
    },
    {
        "english": "Until tomorrow, business world.",
        "french": "A demain, monde des affaires.",
        "duala": "",
        "ghomla": "fà' gɔ̂ ti pə də̀mcá' yó",
        "bulu": "aakítí, sî mam",
        "basaa": "Yàni, à mbɔk lìkɔ̀t ŋ̀kùs.",
    },
    {
        "english": "Mistakes are lessons learned.",
        "french": "Les erreurs sont des leçons apprises.",
        "duala": "",
        "ghomla": "mhɔ̌ há mntɔ̌k",
        "bulu": "bivus bí nə ayə́ə́lə́ yā nyɔŋ",
        "basaa": "Dìhòhà di yê m̀ɓɔ̀ŋɔ̂k i yìgîl.",
    },
    {
        "english": "Leadership skills in action.",
        "french": "Compétences en leadership en action.",
        "duala": "",
        "ghomla": "mfà̀' pəpùŋ gɔ̌ tàm dzə̌",
        "bulu": "ǹyɔŋán ngul yǎ tə́bə ósū",
        "basaa": "Lìɓâk li kɛ̀nà ɓòt nì njɛ̌l màɓɔ̀ŋɔ̀k.",
    },
    {
        "english": "Business journey, grateful CEO.",
        "french": "Parcours d'affaires, PDG reconnaissant.",
        "duala": "",
        "ghomla": "ghiŋtə́ fà', tá fà' ghɔ̌'tə̀",
        "bulu": "mbamba abɔ̌ dulu yā ésae, mása a kaŋəsə",
        "basaa": "Njɛ̌l lìkɔ̀t ŋ̀kùs, màsee ma PDG.",
    },
    {
        "english": "Time to leave the office.",
        "french": "Il est temps de quitter le bureau.",
        "duala": "",
        "ghomla": "tàm nə́ ntəm fà'",
        "bulu": "eyɔ̌ŋ yā kólo ndá biasé é kuí yǎ",
        "basaa": "Ŋgɛn ì ŋ̀kɔla lɛ mɛ ńyɔ̀di i tǔn ɓòlo.",
    },
    {
        "english": "Business dinner, networking power.",
        "french": "Dîner d'affaires, pouvoir de réseautage.",
        "duala": "",
        "ghomla": "cə̀n fà' ghə̌ mú' fà'",
        "bulu": "ńdíán wɔ́ kom mam, ngul ésə ya sɔ́ aa bot bə́ maa ",
        "basaa": "Jɛ i liɓɔk ŋ̀kùs, ŋgùy ì lìàdâ.",
    },
    {
        "english": "Sharing success stories confidently.",
        "french": "Partager des réussites en toute confiance.",
        "duala": "",
        "ghomla": "ghamp pê fà' tə̌ pwɔ̀k",
        "bulu": "ə́ kabǎn miǹkabán təkaa wɔ̄ŋ",
        "basaa": "Kàbnana màm nì ńyōnôs nì ɓodôl yɔsô.",
    },
    {
        "english": "Balancing work and personal tasks.",
        "french": "Concilier travail et tâches personnelles.",
        "duala": "",
        "ghomla": "tàmtə̀ fà' pwá mfam' dyə̌",
        "bulu": "ə́ fulan bīsáé aa mǎm yā ndá",
        "basaa": "Ɓɔ̀ŋa ɓòlo nì mìnsɔn minân ǹtoŋ.",
    },
    {
        "english": "Strategic discussions with family.",
        "french": "Discussions stratégiques en famille.",
        "duala": "",
        "ghomla": "mtɔknyə́ pəpùŋ cʉ́m tuŋdyə̌",
        "bulu": "miǹláŋ mí ntáánə́ mam yā ndá bot",
        "basaa": "Mìŋkwɛ̀l mìnsɛŋg i kède ndap-ɓòt.",
    },
    {
        "english": "Balancing work and life.",
        "french": "Concilier travail et vie personnelle.",
        "duala": "",
        "ghomla": " tamtə́ fà' pwá yu dyə̌",
        "bulu": "ə́ fulan bīsáé aa enyiŋ étám",
        "basaa": "Pòòna ɓòlo nì nìŋ. ",
    },
    {
        "english": "Dreaming of business triumphs.",
        "french": "Rêver de triomphes commerciaux.",
        "duala": "",
        "ghomla": "yɔ́ jʉ́m nə́ tɛ́ sim pəpùŋ",
        "bulu": "á yəm bīyə́yə̄m məkabə",
        "basaa": "Ɛ̀mɛ̀l yèmbèl i nyuŋgā.",
    },
    {
        "english": "Ready for a restful sleep.",
        "french": "Prêt pour un sommeil réparateur.",
        "duala": "",
        "ghomla": "cwə lwɔ̌k nə́ hwǐtə̀",
        "bulu": "ǹkoməsán ású óyɔ̄ wɔ́ kom abuí mam",
        "basaa": "Mɛ̀ tee inyùu hìlɔ hi matibla.",
    },
    {
        "english": "Tomorrow brings new opportunities.",
        "french": "Demain apporte de nouvelles opportunités.",
        "duala": "",
        "ghomla": "fɔ̂kdzʉ̌ pwá nwə̌ sə́ myə́",
        "bulu": "aakítí wɔ́ sɔ́ aa mimfefe mí mam",
        "basaa": "Yàni à ńlɔ̀na manjɛ̀l ma mɔndɔ.",
    },
    {
        "english": "Business time, family time.",
        "french": "Temps de travail, temps en famille.",
        "duala": "",
        "ghomla": "cwə̀ nə́ fà' cʉ́m tuŋdyə̌",
        "bulu": "eyɔ̌ŋ yā ésaē, eyɔ̌ŋ yā tabə aa ndá bot",
        "basaa": "Ŋgèdà inyùu lìkɔ̀t ŋ̀kùs, ŋgèdà inyùu ndap-ɓòt.",
    },
    {
        "english": "Proud of entrepreneurial achievements.",
        "french": "Fier des réalisations entrepreneuriales.",
        "duala": "",
        "ghomla": "ŋwɛ̌nyə́ nə́ fà' tsʉ' fà'",
        "bulu": "məvak amú mǎm yā mīsóŋgán mā",
        "basaa": "Màsee inyùu minsɔn mi liɓɔ̄k ŋ̀kùs mɛ̀ ǹyonôs.",
    },
    {
        "english": "Work hard, innovate harder!",
        "french": "Travaillez dur, innovez plus fort !",
        "duala": "",
        "ghomla": "fà' té' ghə̌ potsə̀ sə̌",
        "bulu": "sááne abuí, zǎne aa mimfefe mí mam",
        "basaa": "Sal ŋgàndàk, ɓǎŋ kì lɔ̀ɔ̀ ŋgàndàk.",
    },
    {
        "english": "Kindness in business matters.",
        "french": "La gentillesse en affaires.",
        "duala": "",
        "ghomla": "nə́ ŋwɛ̌nyə tsʉ́' fà' pɔŋ",
        "bulu": "mbamba fúlú ə́ mǎm bə mɔné",
        "basaa": "Lɔŋgɛ̂ i ŋɛ̄m i kède lìkɔ̀t ŋ̀kùs.",
    },
    {
        "english": "Continuous learning fuels success.",
        "french": "L’apprentissage continu alimente la réussite.",
        "duala": "",
        "ghomla": "nə́́ pə̌ dânyə̀ ghə fà' pə́ boŋ",
        "bulu": "ǹyéán eyɔŋ ésə wɔ́ sɔ́ aa nkabán",
        "basaa": "Ŋgàndàk yìgîl ì ńtī yembèl i màm.",
    },
    {
        "english": "Challenges breed entrepreneurial strength.",
        "french": "Les défis engendrent la force entrepreneuriale.",
        "duala": "",
        "ghomla": "fà' té' há gruə̀",
        "bulu": "məsə́ŋgán má bíáy ngūl məsóŋgán",
        "basaa": "Mìŋkàgdà mi mâm mi ḿɓɔ̀ŋ ŋgùy ì ǹsɔn i liɓɔk ŋ̀kùs lɛ i lɔɔ̄.",
    },
    {
        "english": "Anticipating a fruitful weekend!",
        "french": "En attendant un week-end fructueux !",
        "duala": "",
        "ghomla": "nə́ pə̌ pyáp myə́ŋ gâpdzǔ",
        "bulu": "ńté bíá yaŋgə mbamba amanə́ sɔ́ndo",
        "basaa": "Puhɛ lisuk li sɔndî li matam.",
    },
    {
        "english": "Reflecting on entrepreneurial endeavors.",
        "french": "Réflexion sur les efforts entrepreneuriaux.",
        "duala": "",
        "ghomla": "msɛ̌ nwə̂ nə́ grʉ' fà'",
        "bulu": "m̀fasán ású mǎm yā mīǹsóŋán",
        "basaa": "Pèk inyùu ǹsɔn i likɔ̀t ŋ̀kùs.",
    },
    {
        "english": "Tomorrow, more ventures await.",
        "french": "Demain, d'autres projets vous attendent.",
        "duala": "",
        "ghomla": "fɔ̂kdzʉ̌ shə̌ mfà' wə byáp wɔkpə́",
        "bulu": "aakítí, miǹsóŋán mīfə́ míá yangə míā",
        "basaa": "Yàni, màɓɔgɔ̂k màpɛ ma ḿɓɛ̀mb ɓee.",
    },
    {
        "english": "Cherishing successful moments.",
        "french": "Chérir les moments réussis.",
        "duala": "",
        "ghomla": "pǎtə cwə̌ pəpùŋ",
        "bulu": "nyəŋələ̌ biyɔŋ bí nkabán",
        "basaa": "Sìŋgɛ màŋgèdà ma yembèl",
    },
    {
        "english": "Balancing business and personal life.",
        "french": "Concilier vie professionnelle et vie personnelle.",
        "duala": "",
        "ghomla": "tàmtə̀ fà' pwá mfam' dyə̌",
        "bulu": "m̀fulán ényiŋ bísaé aa enyǐŋ mot émiēn",
        "basaa": "Pòòna lìkɔ̀t ŋ̀kùs lòŋnì nìŋ yɔŋ.",
    },
    {
        "english": "Bedtime routine for a sharp mind.",
        "french": "Routine du coucher pour un esprit vif.",
        "duala": "",
        "ghomla": "nə́ pə̌ nwɔ̀ŋ kó nə́ hwǐtə̀ zhyənwə̀",
        "bulu": "mǎm yā mbōmbán ású ńkáŋgə̄ ńsísim",
        "basaa": "Lìmɛ̀yà ŋgɛŋ nàŋ li ńyìbil ɓɔŋā.",
    },
    {
        "english": "Entrepreneurial bedtime rituals.",
        "french": "Rituels entrepreneuriaux du coucher.",
        "duala": "",
        "ghomla": "ba' pu ji ghə̌ tə́ nwɔŋ kǒ lə́",
        "bulu": "mətǔm mīsóŋgán yā mbōmbán ",
        "basaa": "Lìkàŋ li ŋgedà hìlɔ inyùu ǹsɔn i liɓɔk ŋ̀kùs.",
    },
    {
        "english": "Dream big, sleep well.",
        "french": "Rêvez grand, dormez bien.",
        "duala": "",
        "ghomla": "po yɔ jʉ̀m gwyə́, di' pəpùŋ",
        "bulu": "yəmáne abəŋ bíyə́yə̄m",
        "basaa": "Ɛ̀mɛl mbom mâm, nàŋal lɔŋgɛ̂.",
    },
    {
        "english": "Gratitude for a thriving business.",
        "french": "Gratitude pour une entreprise florissante.",
        "duala": "",
        "ghomla": "mətokwa nə yəŋ boŋ tàm",
        "bulu": "akíba amú éwólo ndá ekom bíə́m",
        "basaa": "Màyègà inyùu ndap ɓòlo ì ì ńnūm mbondì.",
    },
    {
        "english": "Tomorrow's entrepreneurial adventures await.",
        "french": "Les aventures entrepreneuriales de demain vous attendent.",
        "duala": "",
        "ghomla": "fà' fɔkdzǔ bo byáp wɔ́",
        "bulu": "mǎm yā məsóŋgán yā aakítí má yangə míā",
        "basaa": "Mànjɛ̀l ma liɓɔk ŋ̀kùs ma yani ma ḿɓɛ̀mb ɓes.",
    },
    {
        "english": "Thankful for the entrepreneurial journey.",
        "french": "Merci pour le parcours entrepreneurial.",
        "duala": "",
        "ghomla": "mətokwa nə yəŋ boŋ tyɛ̌' fà'",
        "bulu": "akíba amú dulǔ míǹsóŋán",
        "basaa": "Mɛ̀ ǹyega ŋgandàk inyùu ìni kɛl ɓòlo i likɔ̀t ŋ̀kùs.",
    },
    {
        "english": "Every moment fuels ambition.",
        "french": "Chaque instant alimente l’ambition.",
        "duala": "",
        "ghomla": "bǎyâ tàm lə́ kwǐ' mkɛ̌nyə́",
        "bulu": "eyɔŋ ésə já və̄ mīǹsóŋán m̀fefě ngul",
        "basaa": "Màŋgèdà mɔmasô ma ńyōnos mɛ̂ nì màhɔnɔ̂l ma mbom nìŋ.",
    },
    {
        "english": "Let's make pancakes for breakfast!",
        "french": "Préparons des crêpes pour le petit-déjeuner !",
        "duala": "",
        "ghomla": "pə̌ nɛ̌ mkrɛ̀p nə́ bvə̀nyə́ shwə̀",
        "bulu": "ńyámáni bə crɛ́p ású étyam akak",
        "basaa": "Di ɓɔ̄ŋ pɛ̀ŋkêk inyùu jɛ-bikɛkɛ̀là.",
    },
    {
        "english": "Stir the batter, it's fun.",
        "french": "Remuez la pâte, c'est amusant.",
        "duala": "",
        "ghomla": "pó sopnyə́ jǎgle , á  mà' mtyə̌ŋ",
        "bulu": "fulukû pâte, jǎm tē yá wɔle",
        "basaa": "Lìɓòò ndɔ̀mba, halâ à ńnòhla lɛ.",
    },
    {
        "english": "Dad, can I crack eggs?",
        "french": "Papa, je peux casser des œufs ?",
        "duala": "",
        "ghomla": "tá, bə́ myə́ kò' pə́mgɔ̌p á?",
        "bulu": "pəpá, yə mə nə búé mətyi mə́kúp?",
        "basaa": "À itâ, ɓàa mɛ̀ ńlà ɓɔl macɛ̀ɛ?",
    },
    {
        "english": "Yay, it's breakfast time!",
        "french": "Ouais, c'est l'heure du petit-déjeuner !",
        "duala": "",
        "ghomla": " weé! yə̀ŋ tàm nə́ bvənyə́ shwə́!",
        "bulu": "uais, awɔlɔ étyam akak é kuí yǎ",
        "basaa": "Ŋ̀ŋ̌, ŋgèdà jɛ i kɛkɛ̀là ìni.",
    },
    {
        "english": "Smells yummy, what's cooking?",
        "french": "Ça sent bon, qu'est-ce qui mijote ?",
        "duala": "",
        "ghomla": "kə́ bò dzô'? á bo dámnyə́",
        "bulu": "abəŋ ényum, jé yá tɔk?",
        "basaa": "I ńnɛ̀, kii i ḿpèl?",
    },
    {
        "english": "Pass me the sugar, please.",
        "french": "Passe-moi le sucre, s'il te plaît.",
        "duala": "",
        "ghomla": "po há shúkǎ bem, səsò",
        "bulu": "támə́ ma və́ miǹkók eǹgóngɔ̄l",
        "basaa": "Lèes lɛ mɛ̀ ɓɔ̀mbɔ, sɔhɔ.",
    },
    {
        "english": "Mix the ingredients like this.",
        "french": "Mélangez les ingrédients comme ceci.",
        "duala": "",
        "ghomla": "po tàmtə́ mtsə́ ná' pó'",
        "bulu": "fulân bikidəga aná",
        "basaa": "Pòòna bìkùlɛ haana.",
    },
    {
        "english": "Breakfast is ready, come!",
        "french": "Le petit déjeuner est prêt, venez !",
        "duala": "",
        "ghomla": "wə̃ nə́ bvənyé shwə̌ tsə́, pò sǒ'",
        "bulu": "étyam akak é ntɔ̂ nkoməsán, zǎne ",
        "basaa": "Bìjɛk bi kɛkɛ̀là bi ḿɓɛ̄l, lɔ̀ga!",
    },
    {
        "english": "Time for family feast! ",
        "french": "C'est l'heure de la fête en famille !",
        "duala": "",
        "ghomla": "yə̀ŋ tàm dǐnà cʉ́m tuŋdyə̌.",
        "bulu": "awɔlɔ̌ yā bɔ ábōk é ndá bot é kuí ya",
        "basaa": "Ŋgɛŋ ŋgànd ì ndap-ɓòt ì ŋ̀kɔlà.",
    },
    {
        "english": "What's for lunch, Mom?",
        "french": "Qu'est-ce qu'il y a pour le déjeuner, maman ?",
        "duala": "",
        "ghomla": "pə gɔ́ pfaə̌ kə́ mɔkcʉ́ má?",
        "bulu": "étyam akak é nə jé?",
        "basaa": "Kii inyùu jɛ i kɔsì îni?",
    },
    {
        "english": "Let's chop veggies together.",
        "french": "Hachons des légumes ensemble.",
        "duala": "",
        "ghomla": "pə́ pə́mtə́ já'tə́ jap",
        "bulu": "Jé biá dí étyam akak, á nyia?",
        "basaa": "Di kidgaga bààm ǹtoŋ.",
    },
    {
        "english": "I love the smell of onions.",
        "french": "J'adore l'odeur des oignons.",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ zhʉ̌ə́ ánǔsì",
        "bulu": "ma nyəə enyǔm bə́ ányɔn",
        "basaa": "Mɛ̀ ŋ́gwēs jîŋ ì màlàŋ.",
    },
    {
        "english": "Stir the soup, don't spill.",
        "french": "Remuez la soupe, ne la renversez pas.",
        "duala": "",
        "ghomla": "po pwə̌nyə́ ná',ka pó pfyə̌",
        "bulu": "Fɔ́ɔ́né m̀fyáŋ, tə míá sue sí",
        "basaa": "Ɓòòa sûp, nì kop ɓāŋ yɔ̀",
    },
    {
        "english": "Can I taste the soup?",
        "french": "Puis-je goûter la soupe ?",
        "duala": "",
        "ghomla": "pə́ myə́ zhiʉ̌'tə́ ná' á?",
        "bulu": "Yə mə nə fɔ́ɔ́ tyee ḿfyāŋ?",
        "basaa": "Ɓàa mɛ̀ ńlà nɔɔdɛ̄ sûp ɛ̀?",
    },
    {
        "english": "I'll set the table, okay?",
        "french": "Je vais mettre la table, d'accord ?",
        "duala": "",
        "ghomla": "gɔ̌ yáp cə́ŋ təplé, tə́ po' á?",
        "bulu": "ma zu téle tə́bə̄lə, mí wô yǎ?",
        "basaa": "Mɛ̀ gatībil têblè, ǹnɔk ɛ?",
    },
    {
        "english": "Pass me the salt, please.",
        "french": "Passe moi le sel s'il te plaît.",
        "duala": "",
        "ghomla": "há mgwɛ́ bə́m, səsò",
        "bulu": "engóngɔ́l támə́ ma və́ ǹkǔ",
        "basaa": "Lèes lɛ mɛ̀ ɓàs, sɔhɔ.",
    },
    {
        "english": "We're a cooking team!",
        "french": "Nous sommes une équipe de cuisine !",
        "duala": "",
        "ghomla": "pyə̌ bə́ pə́ nɛ̌ cə̀ŋ !",
        "bulu": "bí nə ǹsámbá bə́ yâm bidí",
        "basaa": "Dì yè yùm i ńlamb.",
    },
    {
        "english": "Let's bake cookies after lunch.",
        "french": "Préparons des biscuits après le déjeuner.",
        "duala": "",
        "ghomla": "pə́ nɛ̌ biskʉ́ jʉ̀m cə̀ŋ",
        "bulu": "ńyámáne biwole ḿvûsə etyam akak",
        "basaa": "Di lamba bìòlò i mbūs jɛ i kɔsì.",
    },
    {
        "english": "I want to lick spoons!",
        "french": "J'ai envie de lécher des cuillères !",
        "duala": "",
        "ghomla": "gaə̌ wə́ cə́ŋ nə́ tsɛ̌ lú'",
        "bulu": "ma kómbo nyíaň mə̄tók",
        "basaa": "Mɛ̀ gwèe ŋgòŋ i nyaŋâl tok.",
    },
    {
        "english": "Oops, dropped a carrot.",
        "french": "Oups, j'ai laissé tomber une carotte.",
        "duala": "",
        "ghomla": "yeé karɔ́t vʉ̌ sí",
        "bulu": "oops, ma tə́ wuǎ kārót wūá",
        "basaa": "Êy, mɛ̀ ŋ̀wâs kârôt ì kwɔ̂.",
    },
    {
        "english": "Mom, can I peel potatoes?",
        "french": "Maman, je peux éplucher les pommes de terre ?",
        "duala": "",
        "ghomla": "má, pə́ myə̌ kə̀m bvʉ̂ á?",
        "bulu": "məmá nə séle mə̄tótaa?",
        "basaa": "À îni, ɓàa mɛ̀ ńlà sɛbɛl ɓakwɛ̀dɛ̀?",
    },
    {
        "english": "Dad, is it spicy?",
        "french": "Papa, c'est épicé ?",
        "duala": "",
        "ghomla": "tá, a bo cyə̂ á?",
        "bulu": "pəpá, ndóndô anə m̀bə̂ abuí",
        "basaa": "À ìtâ, bi ńlàŋ ɛ̀?",
    },
    {
        "english": "Yummy smells from the oven!",
        "french": "De délicieuses odeurs du four !",
        "duala": "",
        "ghomla": "hmmmmm pǎ' damnyə́",
        "bulu": "mbambǎ binyǔm yā fûr",
        "basaa": "Bìlɔŋgɛ̂ bi manjìŋ bi juu li gâz!",
    },
    {
        "english": "Can I help with the salad?",
        "french": "Puis-je aider avec la salade ?",
        "duala": "",
        "ghomla": "pə myə́ kwǐtə́ wɔ́ saladə̂ á?",
        "bulu": "yə mə vɔ́lo aa salâd?",
        "basaa": "Ɓàa mɛ̀ ńlà hola ni sàlâd ɛ̀?",
    },
    {
        "english": "I love the sound of sizzling.",
        "french": "J'adore le son du grésillement.",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ gǐ ywə́ nɛ́nɛ́",
        "bulu": "Ma nyəə azík grésiləmáŋ",
        "basaa": "Mɛ̀ ŋ́gwēs i ŋùmŋgà i ŋ́kɔ̀gâ.",
    },
    {
        "english": "I'll wash the veggies.",
        "french": "Je vais laver les légumes.",
        "duala": "",
        "ghomla": "gɔ̌ sɔ̀' jap",
        "bulu": "mayə sǒp bīlɔ́k",
        "basaa": "Mɛ̀ gajòa baâm.",
    },
    {
        "english": "Can I pour the milk?",
        "french": "Puis-je verser le lait ?",
        "duala": "",
        "ghomla": "pə́ myə́ pfyə́ mə̀ník á?",
        "bulu": "yə mə nə soě mə̄nyáŋ?",
        "basaa": "Ɓàà mɛ̀ ńlà kop milîk ɛ̀?",
    },
    {
        "english": "Spaghetti twirl challenge!",
        "french": "Défi du tourbillon de spaghetti !",
        "duala": "",
        "ghomla": "nə́ sɔpnyé spagetǐ",
        "bulu": "məsə́ŋgán mə́ nkulu miǹsɔ́ŋ",
        "basaa": "Pèmsan ì ŋgììŋà ǹsòŋ u spàgèti.",
    },
    {
        "english": "I'll taste the sauce.",
        "french": "Je vais goûter la sauce.",
        "duala": "",
        "ghomla": "gɔ̌  zhwǐ'tə́ ná'",
        "bulu": "ma zu tyək ḿfyāŋ",
        "basaa": "Mɛ̀ ganɔ̀ɔ̀dɛ sûp.",
    },
    {
        "english": "Dinner's almost ready, hurry!",
        "french": "Le dîner est presque prêt, dépêchez-vous !",
        "duala": "",
        "ghomla": "cə̀ŋ bwâdzǔ bo gɔ tsə, po lo'nyə́",
        "bulu": "etyam akak é ḿbə́mə bé bɔ̌ne avól",
        "basaa": "Bìjɛk bi kokoa bi tegi, hɔwa!",
    },
    {
        "english": "We made a tasty mess!",
        "french": "Nous avons fait un délicieux gâchis !",
        "duala": "",
        "ghomla": "pə́ nɛ́ bòŋ cə̀ŋ",
        "bulu": "Biá kə́ bɔ̌ mbamba endáman",
        "basaa": "Dì ŋ̀ŋobos gwɔm lɔŋgɛ̂ lɛ.",
    },
    {
        "english": "Can I scoop the ice cream?",
        "french": "Puis-je ramasser la glace ?",
        "duala": "",
        "ghomla": "á ŋwǎ wé á?",
        "bulu": "yə mə nyɔŋə́ glāce?",
        "basaa": "Ɓàa mɛ̀ ńlà ɓada ɓɔdā lìtanga?",
    },
    {
        "english": "I like setting the table.",
        "french": "J'aime mettre la table.",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ nə́ tîŋ təple",
        "bulu": "ma nyəə mə télee tə́bə̄lə",
        "basaa": "Mɛ̀ ŋ́gwēs mɛ̀ ńtibil teblè.",
    },
    {
        "english": "It's a family cooking party!",
        "french": "C'est une fête culinaire en famille !",
        "duala": "",
        "ghomla": "yə̀ŋ dínà ywətsʉ̀ cʉ̀m tuŋdyə̌",
        "bulu": "Anə abók ńnām aa ndá bot",
        "basaa": "Ŋgɛŋ ì ǹlamb ì ndap-ɓòt ìni.",
    },
    {
        "english": "Dad, can I flip burgers?",
        "french": "Papa, je peux retourner des hamburgers ?",
        "duala": "",
        "ghomla": "tá á sɔpnyə́ hàmbugəl á?",
        "bulu": "Pəpá yə mə nə tiŋəlanə́ bə̄ hábúgər?",
        "basaa": "À ìtâ, ɓàa mɛ̀ ńlà ɓoô hamburgɛ̀r ɛ̀?",
    },
    {
        "english": "Who wants to stir fry?",
        "french": "Qui veut faire des sautés ?",
        "duala": "",
        "ghomla": "wə́ bo cə̀ŋ nə́ tàm ywə̌?",
        "bulu": "zá ā kómbo bɔ̌ bə soté?",
        "basaa": "Ǹjɛɛ à ńsòmbol waŋ?",
    },
    {
        "english": "I'll pass you the plates.",
        "french": "Je vais vous passer les assiettes.",
        "duala": "",
        "ghomla": "gɔ̌ há mkɛ̌ bí pó",
        "bulu": "ma kalan wɔ bisóá",
        "basaa": "Mɛ̀ gatī wɛ̂ mìnlɛha.",
    },
    {
        "english": "Time for a cooking adventure!",
        "french": "C'est l'heure d'une aventure culinaire !",
        "duala": "",
        "ghomla": "tá̀m nə́ nɛ́ ywə́",
        "bulu": "awɔlɔ̌ yā yām é kuí yǎ",
        "basaa": "Ŋgɛŋ inyùu ì jòp i ńlāmb ìni,",
    },
    {
        "english": "Can I decorate the cupcakes?",
        "french": "Puis-je décorer les cupcakes ?",
        "duala": "",
        "ghomla": "á nyàptə́ tù' yəŋ á?",
        "bulu": "yə mə nə dup bə̄ cúpcakes?",
        "basaa": "Ɓàa mɛ̀ ńlà ɛ̂ŋg kɔ̂k ì kɔ̀ga?",
    },
    {
        "english": "We make the best pizza!",
        "french": "Nous faisons la meilleure pizza !",
        "duala": "",
        "ghomla": "pyə́ bo ghə̌ bòŋ pikzá",
        "bulu": "bíá bɔ̌ pizzza ā daŋ!",
        "basaa": "Dì m̀ɓâŋ piza ì lòòha lam.",
    },
    {
        "english": "Mom, can I serve?",
        "french": "Maman, je peux servir ?",
        "duala": "",
        "ghomla": "má á gàp cə̀ŋ á?",
        "bulu": "məmá, yə mə nə səŋ?",
        "basaa": "À îni, ɓàa mɛ̀ ńlà sɛ̂ŋ ɛ̀ ?",
    },
    {
        "english": "I love family cooking!",
        "french": "J'adore la cuisine familiale !",
        "duala": "",
        "ghomla": "gaə̌ ŋkùŋ kǐsîm tuŋdyə̌ ",
        "bulu": "ma nyəə ǹnám ndá bot",
        "basaa": "Mɛ̀ ŋ́gwēs ńlamb i ndap-ɓòt.",
    },
    {
        "english": "Let's make a fruit salad.",
        "french": "Préparons une salade de fruits.",
        "duala": "",
        "ghomla": "pə̌ nyáptə́ mtɔ̌mtsə́",
        "bulu": "ńyámáne salâd bibumá",
        "basaa": "Di ɓɔŋa salâd ì màtam.",
    },
    {
        "english": "I'll help wash the dishes.",
        "french": "Je vais aider à faire la vaisselle.",
        "duala": "",
        "ghomla": "gɔ̌ hwǐtə́ nə́ sɔ̌k  potsə́",
        "bulu": "me vɔ́lo sǒp bīsoá",
        "basaa": "Mɛ̀ gahōla i jòwà bìpân.",
    },
    {
        "english": "Pancakes for dinner, hooray!",
        "french": "Crêpes pour le dîner, hourra !",
        "duala": "",
        "ghomla": "krɛ̌p bə cə̀ŋ bwâdzʉ̌",
        "bulu": "Bə crɛ̌p ásū etyam akak, húra!",
        "basaa": "Pɛnkek inyùu jɛ i kokoa, halà ni!",
    },
    {
        "english": "Mom, can I pour juice?",
        "french": "Maman, je peux verser du jus ?",
        "duala": "",
        "ghomla": "má́ myə́ pfyə ghʉ́ à? ",
        "bulu": "məmá yə mə nə soe jus?",
        "basaa": "À îni, mɛ̀ ńlà hɔɔ̂ maɔ̀k ma matam ɛ?",
    },
    {
        "english": "Dad, this soup is amazing!",
        "french": "Papa, cette soupe est incroyable !",
        "duala": "",
        "ghomla": "tá yəŋ ná' poŋ te'",
        "bulu": "pəpá, ḿfyáŋ wu ó nə m᷆bə̂ abəŋ",
        "basaa": "À ìtâ, i sûp ìni ì ńnɛ̀ lɛ.",
    },
    {
        "english": "Cooking with family is awesome!",
        "french": "Cuisiner en famille, c'est génial !",
        "duala": "",
        "ghomla": "nə́ nɛ̌ ywətsǔ pwá tuŋdyə̌ ba pòŋ",
        "bulu": "ə́ yām bīdí aa ndá bot, anə abə̌ŋ jam",
        "basaa": "Lamb lòŋnì ndap-ɓòt lɔŋgɛ̂ lɛ.",
    },
    {
        "english": "Goodnight, I'm stuffed!",
        "french": "Bonne nuit, je suis bourré !",
        "duala": "",
        "ghomla": "po tí pəpùŋ gaə̌ zhwə́",
        "bulu": "mbamba alú, mə́ jáe yǎ",
        "basaa": "Nàŋ ì lam, mɛ̀ yè ǹyɔnɔ̂k!",
    },
    {
        "english": "Let's play soccer after school.",
        "french": "Jouons au football après l'école.",
        "duala": "",
        "ghomla": "səkú mǐ pə̌ tàm bǎlɔŋ",
        "bulu": "ńléáne ebumá ə́ mvúsə sikólo",
        "basaa": "Di tuk bɔ̂l i mbūs sùgulù.",
    },
    {
        "english": "Time for swimming practice, yay!",
        "french": "C'est l'heure de s'entraîner à la natation, ouais !",
        "duala": "",
        "ghomla": "tàm nə danyə́ nə́ fyə́ cʉ́ shyə",
        "bulu": "awɔlɔ̌ yā yée məjɔ́k é kuí yǎ, wê",
        "basaa": "Ŋgɛŋ ì ǹhɔga tɔy ìni, halà ni!",
    },
    {
        "english": "Mom, I love gymnastics class.",
        "french": "Maman, j'adore les cours de gymnastique.",
        "duala": "",
        "ghomla": "má gaə̌ ŋkùŋ nə́ pwə̌nyə́",
        "bulu": "məmá, ma nyəə ayə́ə́lə́ Gymnastique",
        "basaa": "À îni, mɛ̀ ŋ́gwēs yigîl i makwasi.",
    },
    {
        "english": "Off to the park for basketball.",
        "french": "En route pour le parc pour jouer au basket.",
        "duala": "",
        "ghomla": "gaə̌ mə̂jə̌  nə́ ghɔ̌ ntám bâlɔ̌ŋ sàpgó",
        "bulu": "ə́ zə̄n ya pârk ású baskɛ́t",
        "basaa": "I ńjɛ̌l pârk inyùu ì tùk bàskɛ̂t",
    },
    {
        "english": "Soccer game with friends, fun!",
        "french": "Match de football entre amis, amusant !",
        "duala": "",
        "ghomla": "balɔ̌ŋ pwǎ msǒ ba mà' mtǐŋ",
        "bulu": "ńléán ébumá aa bəmvóe, jǎm məvak",
        "basaa": "Lìtùk bɔ̂l lòŋnì màwanda, jàm lìlam!",
    },
    {
        "english": "Jump rope before dinner, okay?",
        "french": "Sauter à la corde avant le dîner, d'accord ?",
        "duala": "",
        "ghomla": "pǒ lə́ŋ gwə̌ tə́ dzʉ̌ cə̀ŋ bwâdzʉ̌?",
        "bulu": "ə́ bāŋ ńkɔ̌l ósúsúa ǹdíán, sə nálē? ",
        "basaa": "Di hima ŋ̀kòò ŋ̀waa jɛ i kokoâ, nì ǹnɔgɛ?",
    },
    {
        "english": "Bike ride with dad, hooray!",
        "french": "Balade à vélo avec papa, hourra !",
        "duala": "",
        "ghomla": "yiŋtə́ məkəlɔ̀ŋ pwá tá",
        "bulu": "Dulu ə́ miǹsíni bía pəpá, húra!",
        "basaa": "Ǹhomok lòŋnì ìtâ i tòtòs, halà ni!",
    },
    {
        "english": "Exercise makes me feel strong.",
        "french": "L’exercice me fait me sentir fort.",
        "duala": "",
        "ghomla": "fà' grʉ' ghə mò tyɔ̌",
        "bulu": "ésaé yá və̄ ma ngul nyúl",
        "basaa": "Ǹsɔn i minsòn u ɓɔ̀ŋ lɛ mɛ ńnôgda lɛ mɛ̀ ńlɛ̀t.",
    },
    {
        "english": "Join me for a jog?",
        "french": "Me rejoindre pour un jogging ?",
        "duala": "",
        "ghomla": "po sɔ̌' pə̂ lǐŋtə́",
        "bulu": "yə we zú kɔɔ mǎ ású jógin?",
        "basaa": "Ù ŋ́kɔ̄p mɛ̂ inyùu ì kɛ̀ ŋ̀gweê?",
    },
    {
        "english": "Yoga before bedtime, calm.",
        "french": "Yoga avant le coucher, calme.",
        "duala": "",
        "ghomla": "nə́ sə́ŋtə́ nə̌ tə́ dí ba pùŋ",
        "bulu": "Yogá tə yén bí kələ bómbo sí, evóvɔe",
        "basaa": "Yogà bisū bi ŋgɛŋ ì nàŋ, ŋwɛ̀ɛ!",
    },
    {
        "english": "Sports day at school, exciting!",
        "french": "Journée sportive à l'école, passionnante !",
        "duala": "",
        "ghomla": "tyɛ́' dʉ̌ səkú bòŋ te'",
        "bulu": "amosə́ spɔ̂r é sikólo,abəŋ!",
        "basaa": "Kɛl ì màkwasi i sùgulù, nyàmndà! ",
    },
    {
        "english": "Climbing trees is super cool.",
        "french": "Grimper aux arbres, c'est super cool.",
        "duala": "",
        "ghomla": "nə́ kwɔ̌' tsə́ tà'tsə̂ ba pùŋ",
        "bulu": "m᷆bə́tán bīlē ó nə m᷆bə̂ abəŋ",
        "basaa": "Bìɛ inyùu hɔgdɛ̀ bi yê lɔŋgɛ̂ kìkìi yɔ̀m ipɛ.",
    },
    {
        "english": "Let's race to the finish!",
        "french": "Courons jusqu'à l'arrivée !",
        "duala": "",
        "ghomla": "pə̌ khujʉ̌ tə̂ kə̌m",
        "bulu": "ńkə́láni m̀bíl aa kə́kuī məmanə́",
        "basaa": "Ŋwǎs lɛ pèmsan ì ŋ̀gwee i māl.",
    },
    {
        "english": "Playing catch with my brother.",
        "french": "Je joue au catch avec mon frère.",
        "duala": "",
        "ghomla": "gaə̌ bo dò' grʉ́' pwá fə̌ à",
        "bulu": "bía mɔ̌jāŋ bíá bɔ kátch",
        "basaa": "Mɛ̀ ńtùk kâc lòŋnì mǎnkeē.",
    },
    {
        "english": "Tennis match at the club.",
        "french": "Match de tennis au club.",
        "duala": "",
        "ghomla": "cù'tə̀ balɔ̌ŋ kàm ywə́",
        "bulu": "ǹléán tenís é nsəŋ wá yian",
        "basaa": "Mâc i tenîs i klɔ̂b.",
    },
    {
        "english": "Martial arts class is awesome.",
        "french": "Le cours d'arts martiaux est génial.",
        "duala": "",
        "ghomla": "səkú nə́ dǎnyə́ grǔ' ba puŋ",
        "bulu": "ayə́ə́lə́ ndūm é nə m᷆bə̂ abəŋ",
        "basaa": "Yìgîl i likɛŋgɛ li bisàŋ i yē lɔŋgɛ lɛ.",
    },
    {
        "english": "Rollerblading is so much fun!",
        "french": "Le roller, c'est tellement amusant !",
        "duala": "",
        "ghomla": "nə́ pwənyə́ mà' mtǐŋ té'",
        "bulu": "Róllər aa wɔle abuí",
        "basaa": "Ǹtùk i rolɛ̀r i ńnòhla lɛ.",
    },
    {
        "english": "Trampoline time, bounce high!",
        "french": "C'est l'heure du trampoline, rebondissez haut !",
        "duala": "",
        "ghomla": "yə̀̀ŋ tàm rampoliŋ po líŋ",
        "bulu": "awɔlɔ̌ trampolíne é kuí yǎ, bətááne báŋ",
        "basaa": "Ŋgɛŋ ì tràmpòlîn ìni, hima i ŋgìi!",
    },
    {
        "english": "Hula hoop challenge, let's go!",
        "french": "Défi Hula Hoop, c'est parti !",
        "duala": "",
        "ghomla": "fò'tə́ liŋ; a yə́ lə̌",
        "bulu": "ǹdaŋán húla hoop, ńkə̄láne aa nyə́",
        "basaa": "Pèmsan i hula hûp, di kɛngaga!",
    },
    {
        "english": "Volleyball game with neighbors.",
        "french": "Match de volley avec les voisins.",
        "duala": "",
        "ghomla": "balɔ̌ŋ  sàpgó pwǎ gɛ́ bedyə̌",
        "bulu": "ǹléán volleyball aa bəmvóé",
        "basaa": "Ǹtùk i volêbɔ̂l lòŋnì ɓòt ɓa liɓok.",
    },
    {
        "english": "Walking the dog, stay active!",
        "french": "Promener le chien, restez actif !",
        "duala": "",
        "ghomla": "po lə̌ mə̂bvʉ̌ʉ kəkǎ;nə cwə̌ bə́ fà'",
        "bulu": "Wulu aa mvú, tabáne ojəjae",
        "basaa": "Lìkè lòŋnì ŋgwɔ, ù ńyìŋghà digî.",
    },
    {
        "english": "Can we try ice skating?",
        "french": "Pouvons-nous essayer le patinage sur glace ?",
        "duala": "",
        "ghomla": "bə pə khʉdʉ̌ də̀m shyə à?",
        "bulu": "yə bí nə vəələ̌ sende é glāce?",
        "basaa": "Ɓàa dì ńlà nɔɔdɛ luk liɓam li matangâ ?",
    },
    {
        "english": "Play tag, I'm the fastest!",
        "french": "Jouez à chat, je suis le plus rapide !",
        "duala": "",
        "ghomla": "nə́ fyə́ gaə̌ dòknyə́",
        "bulu": "bivoé bí ésíŋgi, mǎ mā daŋ osəsa",
        "basaa": "Ǹtùk u siŋgâ, mɛ̀ ńhɔɔ̂ ì lɔ̀ɔ̀ ɓèe.",
    },
    {
        "english": "Karate kicks in the backyard.",
        "french": "Le karaté donne des coups de pied dans la cour.",
        "duala": "",
        "ghomla": "mkə̀m də̌ mkwə̌",
        "bulu": "bikúta bí karaté ńsəŋ",
        "basaa": "Kàratè ì ńtī mincɛ̀ŋ i mbēgde.",
    },
    {
        "english": "Handstand practice in the garden.",
        "french": "Pratique du poirier dans le jardin.",
        "duala": "",
        "ghomla": "nə́ fyə́́ bhəné",
        "bulu": "ǹyéán ḿbeán mə̄sam é ngátan",
        "basaa": "Lìtee wɔ̀ɔ i wɔ̌m i biɓɛ̀ɓɛlà.",
    },
    {
        "english": "Zumba dance in the living room.",
        "french": "Danse Zumba dans le salon.",
        "duala": "",
        "ghomla": "nəŋ dyə̌ bá pùŋ",
        "bulu": "abók zúmba ábā",
        "basaa": "Lìsak Zumbà i kùmba.",
    },
    {
        "english": "Let's have a mini golf match.",
        "french": "Faisons un match de mini-golf.",
        "duala": "",
        "ghomla": "pə tám məywə̌ bâlɔŋ",
        "bulu": "Ńléáne gɔ̂lf mɔnə́ dzóm",
        "basaa": "Lɔ̀ga di tuga gɔ̂lf ndèk.",
    },
    {
        "english": "Frisbee with friends, hooray!",
        "french": "Frisbee entre amis, hourra !",
        "duala": "",
        "ghomla": "fyə̌ cəcə̀ msǒ yeu'",
        "bulu": "bivoe míǹtáŋán ézə̄zaŋ bə́mvóé, húrra!",
        "basaa": "Frìsbî lòŋnì màwanda, halà ni!",
    },
    {
        "english": "Archery practice today, aim.",
        "french": "Entraînement de tir à l'arc aujourd'hui, visez.",
        "duala": "",
        "ghomla": "lǎnyə̀ fə̀ŋ khə̂ bə́ tyɔ̌'",
        "bulu": "ǹyéán ḿbəlán aa m̀fan də́n, lúmáne",
        "basaa": "Lìlɛ̀ŋ m̀pàn lɛ̀n, gwes.",
    },
    {
        "english": "Hopscotch in the driveway, jump!",
        "french": "Marelle dans l'allée, saute !",
        "duala": "",
        "ghomla": "málìŋ bə pú khʉɔ́ tám",
        "bulu": "ála vúbadé é mə̄kāá, báŋə́",
        "basaa": "Lìnyùgɛ̀ hìɓàŋ nì màkòò, him!",
    },
    {
        "english": "Swing set time, reach high.",
        "french": "Swing régler le temps, atteindre haut.",
        "duala": "",
        "ghomla": "nyáptə tám , lə́n te tsə̂",
        "bulu": "ndə́ŋdə́ŋ nkɔló é kom éyɔŋ, é kuī yóp",
        "basaa": "Swîŋ ì ḿɓɔ̄k ŋgedà, ɓɔl i ŋgìi.",
    },
    {
        "english": "Skipping stones at the pond.",
        "french": "Sauter des pierres à l'étang.",
        "duala": "",
        "ghomla": "lə́ŋ mgwɔ̌' shyə",
        "bulu": "é bāŋ bibǎŋ étāŋ",
        "basaa": "Lìhim màŋgɔ̀k i yìmb.",
    },
    {
        "english": "Fun day at the skatepark.",
        "french": "Journée amusante au skatepark.",
        "duala": "",
        "ghomla": "tyɛ́̌'dzǔ mci",
        "bulu": "Amosə́ wá wɔle é skátə́park",
        "basaa": "Kɛl ì ǹtùk i wɔ̌m i liɓam (Sketpârk).",
    },
    {
        "english": "Soccer drills at the field.",
        "french": "Exercices de football sur le terrain.",
        "duala": "",
        "ghomla": "pə̌ tám balɔ̂ŋ káŋ",
        "bulu": "Bisáé yā ébumá ńsəŋ ébumá!",
        "basaa": "Ǹsɔn u bɔ̂l-màkòò i wɔ̌m bɔ̂l.",
    },
    {
        "english": "Tumbling on the mats, whee!",
        "french": "On dégringole sur les tapis, ouf !",
        "duala": "",
        "ghomla": "pə̌ fyə́ də́m mə́tǎ",
        "bulu": " bíá sende é tāpís, ouf!",
        "basaa": "Ɓà ńsɛ̀ndi i bitàpî, wê! ",
    },
    {
        "english": "Basketball shootout at sunset.",
        "french": "Tir de basket-ball au coucher du soleil.",
        "duala": "",
        "ghomla": "bâlɔ̌ŋ sapgò gɔ̌ tám bwâdzǔ",
        "bulu": "Baskɛ́t éyɔŋ vyán wɔ́ dím",
        "basaa": "Lìlɛ̀ŋ bɔ̂l ì bàskɛtbɔ̂l i mbēgde i ɓugajɔp.",
    },
    {
        "english": "Ping pong with family, enjoy!",
        "french": "Ping pong en famille, profitez-en !",
        "duala": "",
        "ghomla": "pə̂ cə̀ŋ tám píŋpɔŋ pu a tuŋdyə̌",
        "bulu": "píŋ pɔŋ ndá bot, fonáne",
        "basaa": "Piŋpɔ̀ŋ lòŋnì ndap-ɓòt, sea!",
    },
    {
        "english": "Play badminton, shuttlecock fun.",
        "french": "Jouez au badminton, amusez-vous au volant.",
        "duala": "",
        "ghomla": "po fyə́ mətwǎ, po cə̀n fə̀ŋ",
        "bulu": "ǹléán badmiton, é vue aa bəmvóé aa bəmvóé",
        "basaa": "Tùga batmintɔ̀n, ni joha kì i vòlâŋ.",
    },
    {
        "english": "Ice cream after a swim.",
        "french": "Glace après une baignade.",
        "duala": "",
        "ghomla": "nwə̌ mwé cwə̀ sɔ̌knə́",
        "bulu": "Glace ḿvúsə ǹjɔ́ɔ́n",
        "basaa": "Ɓɔ̀da lìtanga i mbūs ǹhɔga.",
    },
    {
        "english": "Kickball game with classmates.",
        "french": "Jeu de kickball avec des camarades de classe.",
        "duala": "",
        "ghomla": "fyə̌ kipbal pwǎ msǒ səkú",
        "bulu": "bivoé bi mbímán ébumá bía bəmvóé bâm ",
        "basaa": "Ǹtùk u kikbɔ̂l lòŋnì màwanda ma ndap ì sùgulù.",
    },
    {
        "english": "Let's try rock climbing.",
        "french": "Essayons l'escalade.",
        "duala": "",
        "ghomla": "pə̂ fò' nə́ lwɔ mthə́",
        "bulu": "ńtámáne bə́t é yóp",
        "basaa": "Di ńnɔ̄ɔdɛ lɛ lìhɔgdɛ̀ i maā.",
    },
    {
        "english": "Hike through the nature trail.",
        "french": "Parcourez le sentier nature.",
        "duala": "",
        "ghomla": "pə̂ kə̀ká kə̀ŋ shyə",
        "bulu": "wuláne é nyā zə̄n ásə",
        "basaa": "Kìla kì i ńjɛ̌l ì bìkay.",
    },
    {
        "english": "Windsurfing on a windy day.",
        "french": "Planche à voile par temps venteux.",
        "duala": "",
        "ghomla": "ywə́ nə́ sàm nə́ cwə́ fə̀fá",
        "bulu": "abám mə́vɔ́t éyɔŋ ḿfəbə",
        "basaa": "Lìpùùwɛ̀ i mbɛ̀bi i kɛl mbɛ̀bi.",
    },
    {
        "english": "Tee-ball game with friends.",
        "french": "Partie de tee-ball entre amis.",
        "duala": "",
        "ghomla": "cwə̀ nə́ fəŋnyə́ balɔ̂ŋ cə̀cə́ msǒ",
        "bulu": "bivoe aa ebumá ézə́zāŋə́ bəmvóé",
        "basaa": "Ǹtùk i bɔ̂l ì tê lòŋnì màwanda.",
    },
    {
        "english": "Hop on the trampoline, bounce!",
        "french": "Montez sur le trampoline, rebondissez !",
        "duala": "",
        "ghomla": "po kwɔ' də́m trampolin, po liŋ",
        "bulu": "bə́táne é trampoline, bətáne báŋ",
        "basaa": "Ɓɛda i tràmpòlîn, hima!",
    },
    {
        "english": "Balance beam practice, steady.",
        "french": "Pratique à la poutre, stable.",
        "duala": "",
        "ghomla": "fà̀' bəŋ pyányə́ shye",
        "bulu": "m̀bɔ̌n ésaé á ndǐl é nə́ təkə fóósan",
        "basaa": "Lìlɛ̀ŋ mbìŋg, mɛ̀ omi.",
    },
    {
        "english": "Surfing waves at the beach.",
        "french": "Surfer sur les vagues à la plage.",
        "duala": "",
        "ghomla": "pə lò' fǎshyə kəŋ shyə",
        "bulu": "sende bīkóndók yā ósúē",
        "basaa": "Lìlɛ̀hɛ̀ i maŋgudga i ŋgwāŋ i tuyɛ̂.",
    },
    {
        "english": "Skating at the roller rink.",
        "french": "Patinage à la patinoire.",
        "duala": "",
        "ghomla": "nəŋtə́ nəŋtə́ kəŋ shyə",
        "bulu": "ǹsendán anə́ patin",
        "basaa": "Ŋ̀gwee nì pàtɛ̂ŋ i wɔ̌m i patɛ̂ŋ.",
    },
    {
        "english": "Play soccer with a beach ball.",
        "french": "Jouez au football avec un ballon de plage.",
        "duala": "",
        "ghomla": "po tàm balɔ̌ŋ kə́ŋ shyə",
        "bulu": "é lē ebumá aa ebumá yā eyɔŋə ávə́p",
        "basaa": "Lìtùk bɔ̂l ì màkòò lòŋnì bɔ̂l ì ŋ̀gwaŋ i tuyɛ̂.",
    },
    {
        "english": "Recess time, playground adventures.",
        "french": "Temps de récréation, aventures sur le terrain de jeu.",
        "duala": "",
        "ghomla": "cwə̀̌ nə́ hwǐtə̀, pə̌ ghɔ̌ kàŋ balɔ̂ŋ",
        "bulu": "awɔlɔ áwɔ̌n, éyɔ̌ŋ yā kə́ vuee",
        "basaa": "Ŋgɛŋ nɔ̀yɛ̀ i ńtùk, ǹhomok i wɔ̌m i ńtùk."
    }
];